add_library(client_cstrike SHARED
        ${SE_SRC_PATH}/game/client/c_team_objectiveresource.cpp
        ${SE_SRC_PATH}/game/client/c_team_objectiveresource.h
        ${SE_SRC_PATH}/game/client/c_team_train_watcher.cpp
        ${SE_SRC_PATH}/game/client/c_team_train_watcher.h
        ${SE_SRC_PATH}/game/client/hud_base_account.cpp
        ${SE_SRC_PATH}/game/client/hud_base_account.h
        ${SE_SRC_PATH}/game/client/hud_voicestatus.cpp
        ${SE_SRC_PATH}/game/client/hud_baseachievement_tracker.cpp
        ${SE_SRC_PATH}/game/client/hud_baseachievement_tracker.h
        ${SE_SRC_PATH}/game/client/hud_vote.h
        ${SE_SRC_PATH}/game/client/hud_vote.cpp
        ${SE_SRC_PATH}/game/shared/predicted_viewmodel.cpp
        ${SE_SRC_PATH}/game/shared/predicted_viewmodel.h
        ${SE_SRC_PATH}/game/shared/cstrike/cs_achievement_constants.h
        ${SE_SRC_PATH}/game/shared/cstrike/cs_achievementdefs.h
        ${SE_SRC_PATH}/game/shared/cs_achievements_and_stats_interface.cpp
        ${SE_SRC_PATH}/game/shared/cs_achievements_and_stats_interface.h
        ${SE_SRC_PATH}/game/shared/cstrike/achievements_cs.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/achievements_cs.h
        ${SE_SRC_PATH}/game/shared/cstrike/basecsgrenade_projectile.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/basecsgrenade_projectile.h
        ${SE_SRC_PATH}/game/client/cstrike/buy_presets/buy_preset.cpp
        ${SE_SRC_PATH}/game/client/cstrike/buy_presets/buy_preset_debug.cpp
        ${SE_SRC_PATH}/game/client/cstrike/buy_presets/buy_preset_debug.h
        ${SE_SRC_PATH}/game/client/cstrike/buy_presets/buy_preset_weapon_info.cpp
        ${SE_SRC_PATH}/game/client/cstrike/buy_presets/buy_presets.cpp
        ${SE_SRC_PATH}/game/client/cstrike/buy_presets/buy_presets.h
        ${SE_SRC_PATH}/game/client/cstrike/c_cs_hostage.cpp
        ${SE_SRC_PATH}/game/client/cstrike/c_cs_hostage.h
        ${SE_SRC_PATH}/game/client/cstrike/c_cs_player.cpp
        ${SE_SRC_PATH}/game/client/cstrike/c_cs_player.h
        ${SE_SRC_PATH}/game/client/cstrike/c_cs_playerresource.cpp
        ${SE_SRC_PATH}/game/client/cstrike/c_cs_playerresource.h
        ${SE_SRC_PATH}/game/client/cstrike/c_cs_team.cpp
        ${SE_SRC_PATH}/game/client/cstrike/c_cs_team.h
        ${SE_SRC_PATH}/game/client/cstrike/c_csrootpanel.cpp
        ${SE_SRC_PATH}/game/client/cstrike/c_csrootpanel.h
        ${SE_SRC_PATH}/game/client/cstrike/c_plantedc4.cpp
        ${SE_SRC_PATH}/game/client/cstrike/c_plantedc4.h
        ${SE_SRC_PATH}/game/client/cstrike/c_te_radioicon.cpp
        ${SE_SRC_PATH}/game/client/cstrike/c_te_shotgun_shot.cpp
        ${SE_SRC_PATH}/game/client/cstrike/clientmode_csnormal.cpp
        ${SE_SRC_PATH}/game/client/cstrike/clientmode_csnormal.h
        ${SE_SRC_PATH}/game/shared/cstrike/cs_ammodef.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/cs_ammodef.h
        ${SE_SRC_PATH}/game/shared/cstrike/cs_gamemovement.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/cs_gamerules.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/cs_gamerules.h
        ${SE_SRC_PATH}/game/shared/cstrike/cs_gamestats_shared.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/cs_gamestats_shared.h
        ${SE_SRC_PATH}/game/shared/steamworks_gamestats.cpp
        ${SE_SRC_PATH}/game/shared/steamworks_gamestats.h
        ${SE_SRC_PATH}/game/client/cstrike/cs_in_main.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/cs_player_shared.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/cs_playeranimstate.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/cs_playeranimstate.h
        ${SE_SRC_PATH}/game/client/cstrike/cs_prediction.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/cs_shareddefs.cpp
        ${SE_SRC_PATH}/game/client/cstrike/cs_client_gamestats.cpp
        ${SE_SRC_PATH}/game/client/cstrike/cs_client_gamestats.h
        ${SE_SRC_PATH}/game/shared/cstrike/cs_usermessages.cpp
        ${SE_SRC_PATH}/game/client/cstrike/cs_view_scene.cpp
        ${SE_SRC_PATH}/game/client/cstrike/cs_view_scene.h
        ${SE_SRC_PATH}/game/shared/cstrike/cs_weapon_parse.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/cs_weapon_parse.h
        ${SE_SRC_PATH}/game/client/cstrike/fx_cs_blood.cpp
        ${SE_SRC_PATH}/game/client/cstrike/fx_cs_blood.h
        ${SE_SRC_PATH}/game/client/cstrike/fx_cs_impacts.cpp
        ${SE_SRC_PATH}/game/client/cstrike/fx_cs_knifeslash.cpp
        ${SE_SRC_PATH}/game/client/cstrike/fx_cs_muzzleflash.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/fx_cs_shared.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/fx_cs_shared.h
        ${SE_SRC_PATH}/game/client/cstrike/fx_cs_weaponfx.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/bot/shared_util.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/bot/shared_util.h
        ${SE_SRC_PATH}/game/client/cstrike/vgui_rootpanel_cs.cpp
        ${SE_SRC_PATH}/game/client/cstrike/cs_hud_ammo.cpp
        ${SE_SRC_PATH}/game/client/cstrike/cs_hud_chat.cpp
        ${SE_SRC_PATH}/game/client/cstrike/cs_hud_chat.h
        ${SE_SRC_PATH}/game/client/cstrike/cs_hud_damageindicator.cpp
        ${SE_SRC_PATH}/game/client/cstrike/cs_hud_freezepanel.cpp
        ${SE_SRC_PATH}/game/client/cstrike/cs_hud_freezepanel.h
        ${SE_SRC_PATH}/game/client/cstrike/cs_hud_playerhealth.cpp
        ${SE_SRC_PATH}/game/client/cstrike/cs_hud_playerhealth.h
        ${SE_SRC_PATH}/game/client/cstrike/cs_hud_health.cpp
        ${SE_SRC_PATH}/game/client/cstrike/cs_hud_scope.cpp
        ${SE_SRC_PATH}/game/client/cstrike/cs_hud_target_id.cpp
        ${SE_SRC_PATH}/game/client/cstrike/cs_hud_weaponselection.cpp
        ${SE_SRC_PATH}/game/client/cstrike/hud_account.cpp
        ${SE_SRC_PATH}/game/client/cstrike/hud_armor.cpp
        ${SE_SRC_PATH}/game/client/cstrike/hud_c4.cpp
        ${SE_SRC_PATH}/game/client/cstrike/hud_deathnotice.cpp
        ${SE_SRC_PATH}/game/client/cstrike/hud_defuser.cpp
        ${SE_SRC_PATH}/game/client/cstrike/hud_flashbang.cpp
        ${SE_SRC_PATH}/game/client/cstrike/hud_hostagerescue.cpp
        ${SE_SRC_PATH}/game/client/cstrike/hud_progressbar.cpp
        ${SE_SRC_PATH}/game/client/cstrike/hud_radar.cpp
        ${SE_SRC_PATH}/game/client/cstrike/hud_radar.h
        ${SE_SRC_PATH}/game/client/cstrike/hud_roundtimer.cpp
        ${SE_SRC_PATH}/game/client/cstrike/hud_scenarioicon.cpp
        ${SE_SRC_PATH}/game/client/cstrike/hud_shopping_cart.cpp
        ${SE_SRC_PATH}/game/client/cstrike/cs_hud_achievement_announce.cpp
        ${SE_SRC_PATH}/game/client/cstrike/cs_hud_achievement_announce.h
        ${SE_SRC_PATH}/game/client/cstrike/cs_hud_achievement_tracker.cpp
        ${SE_SRC_PATH}/game/client/cstrike/radio_status.cpp
        ${SE_SRC_PATH}/game/client/cstrike/radio_status.h
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_ak47.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_aug.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_awp.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_basecsgrenade.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_basecsgrenade.h
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_c4.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_c4.h
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_csbase.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_csbase.h
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_csbasegun.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_csbasegun.h
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_deagle.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_elite.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_famas.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_fiveseven.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_flashbang.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_flashbang.h
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_g3sg1.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_galil.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_glock.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_hegrenade.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_hegrenade.h
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_knife.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_knife.h
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_m249.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_m3.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_m4a1.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_mac10.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_mp5navy.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_p228.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_p90.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_scout.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_sg550.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_sg552.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_smokegrenade.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_smokegrenade.h
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_tmp.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_ump45.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_usp.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_xm1014.cpp
        ${SE_SRC_PATH}/game/client/cstrike/VGUI/achievement_stats_summary.cpp
        ${SE_SRC_PATH}/game/client/cstrike/VGUI/achievement_stats_summary.h
        ${SE_SRC_PATH}/game/client/cstrike/VGUI/achievements_page.cpp
        ${SE_SRC_PATH}/game/client/cstrike/VGUI/achievements_page.h
        ${SE_SRC_PATH}/game/client/cstrike/VGUI/stats_summary.cpp
        ${SE_SRC_PATH}/game/client/cstrike/VGUI/stats_summary.h
        ${SE_SRC_PATH}/game/client/cstrike/VGUI/stat_card.cpp
        ${SE_SRC_PATH}/game/client/cstrike/VGUI/stat_card.h
        ${SE_SRC_PATH}/game/client/cstrike/VGUI/base_stats_page.cpp
        ${SE_SRC_PATH}/game/client/cstrike/VGUI/base_stats_page.h
        ${SE_SRC_PATH}/game/client/cstrike/VGUI/match_stats_page.cpp
        ${SE_SRC_PATH}/game/client/cstrike/VGUI/match_stats_page.h
        ${SE_SRC_PATH}/game/client/cstrike/VGUI/lifetime_stats_page.cpp
        ${SE_SRC_PATH}/game/client/cstrike/VGUI/lifetime_stats_page.h
        ${SE_SRC_PATH}/game/client/cstrike/VGUI/bordered_panel.cpp
        ${SE_SRC_PATH}/game/client/cstrike/VGUI/bordered_panel.h
        ${SE_SRC_PATH}/game/client/cstrike/VGUI/backgroundpanel.cpp
        ${SE_SRC_PATH}/game/client/cstrike/VGUI/backgroundpanel.h
        ${SE_SRC_PATH}/game/client/cstrike/VGUI/buymouseoverpanelbutton.h
        ${SE_SRC_PATH}/game/client/cstrike/VGUI/buypreset_imageinfo.cpp
        ${SE_SRC_PATH}/game/client/cstrike/VGUI/buypreset_listbox.cpp
        ${SE_SRC_PATH}/game/client/cstrike/VGUI/buypreset_listbox.h
        ${SE_SRC_PATH}/game/client/cstrike/VGUI/buypreset_panel.cpp
        ${SE_SRC_PATH}/game/client/cstrike/VGUI/buypreset_weaponsetlabel.h
        ${SE_SRC_PATH}/game/client/cstrike/VGUI/career_box.cpp
        ${SE_SRC_PATH}/game/client/cstrike/VGUI/career_box.h
        ${SE_SRC_PATH}/game/client/cstrike/VGUI/career_button.cpp
        ${SE_SRC_PATH}/game/client/cstrike/VGUI/career_button.h
        ${SE_SRC_PATH}/game/client/cstrike/VGUI/counterstrikeviewport.cpp
        ${SE_SRC_PATH}/game/client/cstrike/VGUI/counterstrikeviewport.h
        ${SE_SRC_PATH}/game/client/cstrike/VGUI/cstrikebuyequipmenu.cpp
        ${SE_SRC_PATH}/game/client/cstrike/VGUI/cstrikebuyequipmenu.h
        ${SE_SRC_PATH}/game/client/cstrike/VGUI/cstrikebuymenu.cpp
        ${SE_SRC_PATH}/game/client/cstrike/VGUI/cstrikebuymenu.h
        ${SE_SRC_PATH}/game/client/cstrike/VGUI/cstrikebuysubmenu.h
        ${SE_SRC_PATH}/game/client/cstrike/VGUI/cstrikeclassmenu.cpp
        ${SE_SRC_PATH}/game/client/cstrike/VGUI/cstrikeclassmenu.h
        ${SE_SRC_PATH}/game/client/cstrike/VGUI/cstrikeclientscoreboard.cpp
        ${SE_SRC_PATH}/game/client/cstrike/VGUI/cstrikeclientscoreboard.h
        ${SE_SRC_PATH}/game/client/cstrike/VGUI/cstrikespectatorgui.cpp
        ${SE_SRC_PATH}/game/client/cstrike/VGUI/cstrikespectatorgui.h
        ${SE_SRC_PATH}/game/client/cstrike/VGUI/cstriketeammenu.cpp
        ${SE_SRC_PATH}/game/client/cstrike/VGUI/cstriketeammenu.h
        ${SE_SRC_PATH}/game/client/cstrike/VGUI/cstriketextwindow.cpp
        ${SE_SRC_PATH}/game/client/cstrike/VGUI/cstriketextwindow.h
        ${SE_SRC_PATH}/game/client/cstrike/vgui_c4panel.cpp
        ${SE_SRC_PATH}/game/client/cstrike/vgui_viewc4panel.cpp
        ${SE_SRC_PATH}/game/client/cstrike/VGUI/win_panel_round.cpp
        ${SE_SRC_PATH}/game/client/cstrike/VGUI/win_panel_round.h
        ${SE_SRC_PATH}/game/client/NextBot/C_NextBot.cpp
        ${SE_SRC_PATH}/game/client/NextBot/C_NextBot.h
        ${SE_SRC_PATH}/game/client/game_controls/buymenu.cpp
        ${SE_SRC_PATH}/game/client/game_controls/buysubmenu.cpp
        ${SE_SRC_PATH}/game/client/game_controls/classmenu.cpp
        )
target_include_directories(client_cstrike PRIVATE
        ${SE_SRC_PATH}/game/shared/cstrike/control
        ${SE_SRC_PATH}/game/client/cstrike
        ${SE_SRC_PATH}/game/client/cstrike/control
        ${SE_SRC_PATH}/game/client/cstrike/VGUI
        ${SE_SRC_PATH}/game/shared/cstrike
)
target_compile_definitions(client_cstrike PRIVATE -DCSTRIKE_DLL -DNEXT_BOT)
target_link_libraries(client_cstrike PUBLIC client_base)

add_library(server_cstrike SHARED
        ${SE_SRC_PATH}/game/server/hl2/Func_Monitor.cpp
        ${SE_SRC_PATH}/game/server/h_cycler.cpp
        ${SE_SRC_PATH}/game/server/h_cycler.h
        ${SE_SRC_PATH}/game/shared/predicted_viewmodel.cpp
        ${SE_SRC_PATH}/game/shared/predicted_viewmodel.h
        ${SE_SRC_PATH}/game/shared/hl2/survival_gamerules.cpp
        ${SE_SRC_PATH}/game/server/team_objectiveresource.cpp
        ${SE_SRC_PATH}/game/server/team_objectiveresource.h
        ${SE_SRC_PATH}/game/server/team_spawnpoint.cpp
        ${SE_SRC_PATH}/game/server/team_spawnpoint.h
        ${SE_SRC_PATH}/game/shared/teamplayroundbased_gamerules.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/cs_achievement_constants.h
        ${SE_SRC_PATH}/game/shared/cstrike/achievements_cs.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/achievements_cs.h
        ${SE_SRC_PATH}/game/shared/cstrike/basecsgrenade_projectile.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/basecsgrenade_projectile.h
        ${SE_SRC_PATH}/game/shared/cstrike/cs_ammodef.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/cs_ammodef.h
        ${SE_SRC_PATH}/game/server/cstrike/cs_autobuy.cpp
        ${SE_SRC_PATH}/game/server/cstrike/cs_autobuy.h
        ${SE_SRC_PATH}/game/shared/cstrike/cs_blackmarket.cpp
        ${SE_SRC_PATH}/game/server/cstrike/cs_client.cpp
        ${SE_SRC_PATH}/game/server/cstrike/cs_client.h
        ${SE_SRC_PATH}/game/server/cstrike/cs_eventlog.cpp
        ${SE_SRC_PATH}/game/server/cstrike/cs_gameinterface.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/cs_gamemovement.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/cs_gamerules.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/cs_gamerules.h
        ${SE_SRC_PATH}/game/server/cstrike/cs_gamestats.cpp
        ${SE_SRC_PATH}/game/server/cstrike/cs_gamestats.h
        ${SE_SRC_PATH}/game/shared/cstrike/cs_gamestats_shared.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/cs_gamestats_shared.h
        ${SE_SRC_PATH}/game/shared/steamworks_gamestats.cpp
        ${SE_SRC_PATH}/game/shared/steamworks_gamestats.h
        ${SE_SRC_PATH}/game/server/cstrike/cs_hltvdirector.cpp
        ${SE_SRC_PATH}/game/server/cstrike/cs_player.cpp
        ${SE_SRC_PATH}/game/server/cstrike/cs_player.h
        ${SE_SRC_PATH}/game/server/cstrike/cs_player_resource.cpp
        ${SE_SRC_PATH}/game/server/cstrike/cs_player_resource.h
        ${SE_SRC_PATH}/game/shared/cstrike/cs_player_shared.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/cs_playeranimstate.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/cs_playeranimstate.h
        ${SE_SRC_PATH}/game/server/cstrike/cs_playermove.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/cs_shareddefs.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/cs_shareddefs.h
        ${SE_SRC_PATH}/game/server/cstrike/cs_team.cpp
        ${SE_SRC_PATH}/game/server/cstrike/cs_team.h
        ${SE_SRC_PATH}/game/shared/cstrike/cs_usermessages.cpp
        ${SE_SRC_PATH}/game/server/cstrike/cs_vehicle_jeep.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/cs_weapon_parse.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/cs_weapon_parse.h
        ${SE_SRC_PATH}/game/shared/cstrike/flashbang_projectile.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/flashbang_projectile.h
        ${SE_SRC_PATH}/game/server/cstrike/func_bomb_target.cpp
        ${SE_SRC_PATH}/game/server/cstrike/func_bomb_target.h
        ${SE_SRC_PATH}/game/server/cstrike/func_buy_zone.cpp
        ${SE_SRC_PATH}/game/server/cstrike/func_hostage_rescue.cpp
        ${SE_SRC_PATH}/game/server/cstrike/funfact_cs.cpp
        ${SE_SRC_PATH}/game/server/cstrike/funfact_cs.h
        ${SE_SRC_PATH}/game/server/cstrike/funfactmgr_cs.cpp
        ${SE_SRC_PATH}/game/server/cstrike/funfactmgr_cs.h
        ${SE_SRC_PATH}/game/shared/cstrike/fx_cs_shared.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/fx_cs_shared.h
        ${SE_SRC_PATH}/game/shared/cstrike/hegrenade_projectile.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/hegrenade_projectile.h
        ${SE_SRC_PATH}/game/server/cstrike/info_view_parameters.cpp
        ${SE_SRC_PATH}/game/server/cstrike/item_ammo.cpp
        ${SE_SRC_PATH}/game/server/cstrike/item_assaultsuit.cpp
        ${SE_SRC_PATH}/game/server/cstrike/item_defuser.cpp
        ${SE_SRC_PATH}/game/server/cstrike/item_kevlar.cpp
        ${SE_SRC_PATH}/game/server/cstrike/item_nvgs.cpp
        ${SE_SRC_PATH}/game/server/cstrike/mapinfo.cpp
        ${SE_SRC_PATH}/game/server/cstrike/mapinfo.h
        ${SE_SRC_PATH}/game/server/cstrike/point_surroundtest.cpp
        ${SE_SRC_PATH}/game/server/cstrike/smokegrenade_projectile.cpp
        ${SE_SRC_PATH}/game/server/cstrike/smokegrenade_projectile.h
        ${SE_SRC_PATH}/game/server/cstrike/te_radioicon.cpp
        ${SE_SRC_PATH}/game/server/cstrike/te_shotgun_shot.cpp
        ${SE_SRC_PATH}/game/server/cstrike/te_shotgun_shot.h
        ${SE_SRC_PATH}/game/server/cstrike/holiday_gift.cpp
        ${SE_SRC_PATH}/game/server/cstrike/holiday_gift.h
        ${SE_SRC_PATH}/game/shared/cstrike/cs_urlretrieveprices.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/cs_urlretrieveprices.h
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_ak47.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_aug.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_awp.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_basecsgrenade.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_basecsgrenade.h
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_c4.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_c4.h
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_csbase.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_csbase.h
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_csbasegun.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_csbasegun.h
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_deagle.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_elite.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_famas.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_fiveseven.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_flashbang.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_flashbang.h
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_g3sg1.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_galil.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_glock.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_hegrenade.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_hegrenade.h
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_knife.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_m249.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_m3.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_m4a1.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_mac10.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_mp5navy.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_p228.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_p90.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_scout.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_sg550.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_sg552.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_smokegrenade.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_tmp.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_ump45.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_usp.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/weapon_xm1014.cpp
        ${SE_SRC_PATH}/game/server/cstrike/bot/cs_bot.cpp
        ${SE_SRC_PATH}/game/server/cstrike/bot/cs_bot.h
        ${SE_SRC_PATH}/game/server/cstrike/bot/cs_bot_chatter.cpp
        ${SE_SRC_PATH}/game/server/cstrike/bot/cs_bot_chatter.h
        ${SE_SRC_PATH}/game/server/cstrike/bot/cs_bot_event.cpp
        ${SE_SRC_PATH}/game/server/cstrike/bot/cs_bot_event_bomb.cpp
        ${SE_SRC_PATH}/game/server/cstrike/bot/cs_bot_event_player.cpp
        ${SE_SRC_PATH}/game/server/cstrike/bot/cs_bot_event_weapon.cpp
        ${SE_SRC_PATH}/game/server/cstrike/bot/cs_bot_init.cpp
        ${SE_SRC_PATH}/game/server/cstrike/bot/cs_bot_listen.cpp
        ${SE_SRC_PATH}/game/server/cstrike/bot/cs_bot_manager.cpp
        ${SE_SRC_PATH}/game/server/cstrike/bot/cs_bot_manager.h
        ${SE_SRC_PATH}/game/server/cstrike/bot/cs_bot_nav.cpp
        ${SE_SRC_PATH}/game/server/cstrike/bot/cs_bot_pathfind.cpp
        ${SE_SRC_PATH}/game/server/cstrike/bot/cs_bot_radio.cpp
        ${SE_SRC_PATH}/game/server/cstrike/bot/cs_bot_statemachine.cpp
        ${SE_SRC_PATH}/game/server/cstrike/bot/cs_bot_update.cpp
        ${SE_SRC_PATH}/game/server/cstrike/bot/cs_bot_vision.cpp
        ${SE_SRC_PATH}/game/server/cstrike/bot/cs_bot_weapon.cpp
        ${SE_SRC_PATH}/game/server/cstrike/bot/cs_bot_weapon_id.cpp
        ${SE_SRC_PATH}/game/server/cstrike/bot/cs_gamestate.cpp
        ${SE_SRC_PATH}/game/server/cstrike/bot/cs_gamestate.h
        ${SE_SRC_PATH}/game/server/cstrike/bot/states/cs_bot_attack.cpp
        ${SE_SRC_PATH}/game/server/cstrike/bot/states/cs_bot_buy.cpp
        ${SE_SRC_PATH}/game/server/cstrike/bot/states/cs_bot_defuse_bomb.cpp
        ${SE_SRC_PATH}/game/server/cstrike/bot/states/cs_bot_escape_from_bomb.cpp
        ${SE_SRC_PATH}/game/server/cstrike/bot/states/cs_bot_fetch_bomb.cpp
        ${SE_SRC_PATH}/game/server/cstrike/bot/states/cs_bot_follow.cpp
        ${SE_SRC_PATH}/game/server/cstrike/bot/states/cs_bot_hide.cpp
        ${SE_SRC_PATH}/game/server/cstrike/bot/states/cs_bot_hunt.cpp
        ${SE_SRC_PATH}/game/server/cstrike/bot/states/cs_bot_idle.cpp
        ${SE_SRC_PATH}/game/server/cstrike/bot/states/cs_bot_investigate_noise.cpp
        ${SE_SRC_PATH}/game/server/cstrike/bot/states/cs_bot_move_to.cpp
        ${SE_SRC_PATH}/game/server/cstrike/bot/states/cs_bot_open_door.cpp
        ${SE_SRC_PATH}/game/server/cstrike/bot/states/cs_bot_plant_bomb.cpp
        ${SE_SRC_PATH}/game/server/cstrike/bot/states/cs_bot_use_entity.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/bot/bot.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/bot/bot.h
        ${SE_SRC_PATH}/game/shared/cstrike/bot/bot_constants.h
        ${SE_SRC_PATH}/game/shared/cstrike/bot/bot_hide.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/bot/bot_manager.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/bot/bot_manager.h
        ${SE_SRC_PATH}/game/shared/cstrike/bot/bot_profile.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/bot/bot_profile.h
        ${SE_SRC_PATH}/game/shared/cstrike/bot/bot_util.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/bot/bot_util.h
        ${SE_SRC_PATH}/game/shared/cstrike/bot/shared_util.cpp
        ${SE_SRC_PATH}/game/shared/cstrike/bot/shared_util.h
        ${SE_SRC_PATH}/game/server/cstrike/hostage/cs_simple_hostage.cpp
        ${SE_SRC_PATH}/game/server/cstrike/hostage/cs_simple_hostage.h
        ${SE_SRC_PATH}/game/server/cstrike/cs_nav.h
        ${SE_SRC_PATH}/game/server/cstrike/cs_nav_area.cpp
        ${SE_SRC_PATH}/game/server/cstrike/cs_nav_area.h
        ${SE_SRC_PATH}/game/server/cstrike/cs_nav_generate.cpp
        ${SE_SRC_PATH}/game/server/cstrike/cs_nav_mesh.cpp
        ${SE_SRC_PATH}/game/server/cstrike/cs_nav_mesh.h
        ${SE_SRC_PATH}/game/server/cstrike/cs_nav_pathfind.h
        ${SE_SRC_PATH}/game/server/cstrike/cs_nav_path.cpp
        ${SE_SRC_PATH}/game/server/cstrike/cs_nav_path.h
        ${SE_SRC_PATH}/game/server/NextBot/NextBot.cpp
        ${SE_SRC_PATH}/game/server/NextBot/NextBot.h
        ${SE_SRC_PATH}/game/server/NextBot/NextBotBehavior.h
        ${SE_SRC_PATH}/game/server/NextBot/NextBotManager.cpp
        ${SE_SRC_PATH}/game/server/NextBot/NextBotManager.h
        ${SE_SRC_PATH}/game/server/NextBot/NextBotUtil.h
        ${SE_SRC_PATH}/game/server/NextBot/NextBotKnownEntity.h
        ${SE_SRC_PATH}/game/server/NextBot/NextBotGroundLocomotion.cpp
        ${SE_SRC_PATH}/game/server/NextBot/NextBotGroundLocomotion.h
        ${SE_SRC_PATH}/game/server/NextBot/simple_bot.cpp
        ${SE_SRC_PATH}/game/server/NextBot/simple_bot.h
        ${SE_SRC_PATH}/game/server/NextBot/NextBotBodyInterface.cpp
        ${SE_SRC_PATH}/game/server/NextBot/NextBotBodyInterface.h
        ${SE_SRC_PATH}/game/server/NextBot/NextBotComponentInterface.cpp
        ${SE_SRC_PATH}/game/server/NextBot/NextBotComponentInterface.h
        ${SE_SRC_PATH}/game/server/NextBot/NextBotEventResponderInterface.h
        ${SE_SRC_PATH}/game/server/NextBot/NextBotHearingInterface.h
        ${SE_SRC_PATH}/game/server/NextBot/NextBotIntentionInterface.cpp
        ${SE_SRC_PATH}/game/server/NextBot/NextBotIntentionInterface.h
        ${SE_SRC_PATH}/game/server/NextBot/NextBotInterface.cpp
        ${SE_SRC_PATH}/game/server/NextBot/NextBotInterface.h
        ${SE_SRC_PATH}/game/server/NextBot/NextBotLocomotionInterface.cpp
        ${SE_SRC_PATH}/game/server/NextBot/NextBotLocomotionInterface.h
        ${SE_SRC_PATH}/game/server/NextBot/NextBotVisionInterface.cpp
        ${SE_SRC_PATH}/game/server/NextBot/NextBotVisionInterface.h
        ${SE_SRC_PATH}/game/server/NextBot/NextBotContextualQueryInterface.h
        ${SE_SRC_PATH}/game/server/NextBot/Path/NextBotChasePath.cpp
        ${SE_SRC_PATH}/game/server/NextBot/Path/NextBotChasePath.h
        ${SE_SRC_PATH}/game/server/NextBot/Path/NextBotRetreatPath.h
        ${SE_SRC_PATH}/game/server/NextBot/Path/NextBotPath.cpp
        ${SE_SRC_PATH}/game/server/NextBot/Path/NextBotPath.h
        ${SE_SRC_PATH}/game/server/NextBot/Path/NextBotPathFollow.cpp
        ${SE_SRC_PATH}/game/server/NextBot/Path/NextBotPathFollow.h
        ${SE_SRC_PATH}/game/server/NextBot/Player/NextBotPlayerBody.cpp
        ${SE_SRC_PATH}/game/server/NextBot/Player/NextBotPlayerBody.h
        ${SE_SRC_PATH}/game/server/NextBot/Player/NextBotPlayerLocomotion.cpp
        ${SE_SRC_PATH}/game/server/NextBot/Player/NextBotPlayerLocomotion.h
        ${SE_SRC_PATH}/game/server/NextBot/Player/NextBotPlayer.cpp
        ${SE_SRC_PATH}/game/server/NextBot/Player/NextBotPlayer.h
        ${SE_SRC_PATH}/game/server/NextBot/Behavior/BehaviorBackUp.h
        ${SE_SRC_PATH}/game/server/NextBot/Behavior/BehaviorMoveTo.h
        ${SE_SRC_PATH}/game/server/NextBot/NavMeshEntities/func_nav_prerequisite.cpp
        ${SE_SRC_PATH}/game/server/NextBot/NavMeshEntities/func_nav_prerequisite.h
    )
target_include_directories(server_cstrike PRIVATE
        ${SE_SRC_PATH}/game/shared/cstrike/control
        ${SE_SRC_PATH}/game/server/cstrike
        ${SE_SRC_PATH}/game/server/cstrike/bot
        ${SE_SRC_PATH}/game/server/cstrike/bot/states
        ${SE_SRC_PATH}/game/shared/cstrike
        ${SE_SRC_PATH}/game/shared/cstrike/bot
        ${SE_SRC_PATH}/game/server/cstrike/hostage
        ${SE_SRC_PATH}/game/server/cstrike/control
        )
target_compile_definitions(server_cstrike PRIVATE -DBOTS -DCSTRIKE_DLL -DNEXT_BOT)
target_link_libraries(server_cstrike PUBLIC server_base nav_mesh)

set_target_properties(client_cstrike PROPERTIES
        PREFIX "" OUTPUT_NAME "client")
set_target_properties(server_cstrike PROPERTIES
        PREFIX "" OUTPUT_NAME "server")
install(TARGETS client_cstrike server_cstrike DESTINATION "./cstrike/bin")