add_library(client_base INTERFACE)
target_sources(client_base INTERFACE
        ${SE_SRC_PATH}/game/client/replay/replaycamera.cpp
        ${SE_SRC_PATH}/game/client/replay/replaycamera.h
        ${SE_SRC_PATH}/game/client/replay/cdll_replay.cpp
        ${SE_SRC_PATH}/game/client/replay/cdll_replay.h
        ${SE_SRC_PATH}/common/movieobjects/timeutils.cpp        
        
        ${SE_SRC_PATH}/game/client/hl2/C_Func_Monitor.cpp
        ${SE_SRC_PATH}/game/client/geiger.cpp
        ${SE_SRC_PATH}/game/client/history_resource.cpp
        ${SE_SRC_PATH}/game/client/hud_weapon.cpp
        ${SE_SRC_PATH}/game/client/train.cpp
        #${SE_SRC_PATH}/game/shared/weapon_parse_default.cpp
        ${SE_SRC_PATH}/game/shared/achievement_saverestore.cpp
        ${SE_SRC_PATH}/game/shared/achievementmgr.cpp
        ${SE_SRC_PATH}/game/shared/achievements_hlx.cpp
        ${SE_SRC_PATH}/game/client/achievement_notification_panel.cpp
        ${SE_SRC_PATH}/game/shared/activitylist.cpp
        ${SE_SRC_PATH}/game/client/alphamaterialproxy.cpp
        ${SE_SRC_PATH}/game/shared/ammodef.cpp
        ${SE_SRC_PATH}/game/client/animatedentitytextureproxy.cpp
        ${SE_SRC_PATH}/game/client/animatedoffsettextureproxy.cpp
        ${SE_SRC_PATH}/game/client/animatedtextureproxy.cpp
        ${SE_SRC_PATH}/game/client/AnimateSpecificTextureProxy.cpp
        ${SE_SRC_PATH}/game/shared/animation.cpp
        ${SE_SRC_PATH}/game/shared/base_playeranimstate.cpp
        ${SE_SRC_PATH}/game/shared/baseachievement.cpp
        ${SE_SRC_PATH}/game/client/baseanimatedtextureproxy.cpp
        ${SE_SRC_PATH}/game/client/baseclientrendertargets.cpp
        ${SE_SRC_PATH}/game/shared/basecombatcharacter_shared.cpp
        ${SE_SRC_PATH}/game/shared/basecombatweapon_shared.cpp
        ${SE_SRC_PATH}/game/shared/baseentity_shared.cpp
        ${SE_SRC_PATH}/game/shared/basegrenade_shared.cpp
        ${SE_SRC_PATH}/game/shared/baseparticleentity.cpp
        ${SE_SRC_PATH}/game/shared/baseplayer_shared.cpp
        ${SE_SRC_PATH}/game/shared/baseprojectile.cpp
        ${SE_SRC_PATH}/game/shared/baseviewmodel_shared.cpp
        ${SE_SRC_PATH}/game/client/beamdraw.cpp
        ${SE_SRC_PATH}/game/shared/beam_shared.cpp
        ${SE_SRC_PATH}/public/bone_accessor.cpp
        ${SE_SRC_PATH}/game/client/bone_merge_cache.cpp
        ${SE_SRC_PATH}/game/client/c_ai_basehumanoid.cpp
        ${SE_SRC_PATH}/game/client/c_ai_basenpc.cpp
        ${SE_SRC_PATH}/game/client/c_baseanimating.cpp
        ${SE_SRC_PATH}/game/client/c_baseanimatingoverlay.cpp
        ${SE_SRC_PATH}/game/client/c_basecombatcharacter.cpp
        ${SE_SRC_PATH}/game/client/c_basecombatweapon.cpp
        ${SE_SRC_PATH}/game/client/c_basedoor.cpp
        ${SE_SRC_PATH}/game/client/c_baseentity.cpp
        ${SE_SRC_PATH}/game/client/c_baseflex.cpp
        ${SE_SRC_PATH}/game/client/c_baseplayer.cpp
        ${SE_SRC_PATH}/game/client/c_baseviewmodel.cpp
        ${SE_SRC_PATH}/game/client/c_breakableprop.cpp
        ${SE_SRC_PATH}/game/client/c_colorcorrection.cpp
        ${SE_SRC_PATH}/game/client/c_colorcorrectionvolume.cpp
        ${SE_SRC_PATH}/game/client/c_dynamiclight.cpp
        ${SE_SRC_PATH}/game/client/c_entitydissolve.cpp
        ${SE_SRC_PATH}/game/client/c_entityparticletrail.cpp
        ${SE_SRC_PATH}/game/client/c_env_fog_controller.cpp
        ${SE_SRC_PATH}/game/client/c_env_particlescript.cpp
        ${SE_SRC_PATH}/game/client/c_env_projectedtexture.cpp
        ${SE_SRC_PATH}/game/client/c_env_screenoverlay.cpp
        ${SE_SRC_PATH}/game/client/c_env_tonemap_controller.cpp
        ${SE_SRC_PATH}/game/client/c_fire_smoke.cpp
        ${SE_SRC_PATH}/game/client/c_fish.cpp
        ${SE_SRC_PATH}/game/client/c_func_areaportalwindow.cpp
        ${SE_SRC_PATH}/game/client/c_func_breakablesurf.cpp
        ${SE_SRC_PATH}/game/client/c_func_conveyor.cpp
        ${SE_SRC_PATH}/game/client/c_func_dust.cpp
        ${SE_SRC_PATH}/game/client/c_func_lod.cpp
        ${SE_SRC_PATH}/game/client/c_func_occluder.cpp
        ${SE_SRC_PATH}/game/client/c_func_reflective_glass.cpp
        ${SE_SRC_PATH}/game/client/c_func_rotating.cpp
        ${SE_SRC_PATH}/game/client/c_func_smokevolume.cpp
        ${SE_SRC_PATH}/game/client/c_func_tracktrain.cpp
        ${SE_SRC_PATH}/game/client/c_gib.cpp
        ${SE_SRC_PATH}/game/client/c_hairball.cpp
        ${SE_SRC_PATH}/game/client/c_info_overlay_accessor.cpp
        ${SE_SRC_PATH}/game/client/c_lightglow.cpp
        ${SE_SRC_PATH}/game/client/C_MaterialModifyControl.cpp
        ${SE_SRC_PATH}/game/client/c_particle_system.cpp
        ${SE_SRC_PATH}/game/client/c_physbox.cpp
        ${SE_SRC_PATH}/game/client/c_physicsprop.cpp
        ${SE_SRC_PATH}/game/client/c_physmagnet.cpp
        ${SE_SRC_PATH}/game/client/c_pixel_visibility.cpp
        ${SE_SRC_PATH}/game/client/c_plasma.cpp
        ${SE_SRC_PATH}/game/client/c_playerresource.cpp
        ${SE_SRC_PATH}/game/client/c_point_camera.cpp
        ${SE_SRC_PATH}/game/client/c_point_commentary_node.cpp
        ${SE_SRC_PATH}/game/client/c_props.cpp
        ${SE_SRC_PATH}/game/client/c_ragdoll_manager.cpp
        ${SE_SRC_PATH}/game/client/c_rope.cpp
        ${SE_SRC_PATH}/game/client/c_rumble.cpp
        ${SE_SRC_PATH}/game/client/c_sceneentity.cpp
        ${SE_SRC_PATH}/game/client/c_shadowcontrol.cpp
        ${SE_SRC_PATH}/game/client/c_slideshow_display.cpp
        ${SE_SRC_PATH}/game/client/c_soundscape.cpp
        ${SE_SRC_PATH}/game/client/c_spotlight_end.cpp
        ${SE_SRC_PATH}/game/client/c_sprite.cpp
        ${SE_SRC_PATH}/game/client/c_sprite_perfmonitor.cpp
        ${SE_SRC_PATH}/game/client/c_sun.cpp
        ${SE_SRC_PATH}/game/client/c_team.cpp
        ${SE_SRC_PATH}/game/client/c_tesla.cpp
        ${SE_SRC_PATH}/game/client/c_test_proxytoggle.cpp
        ${SE_SRC_PATH}/game/client/c_user_message_register.cpp
        ${SE_SRC_PATH}/game/client/c_vehicle_choreo_generic.cpp
        ${SE_SRC_PATH}/game/client/c_vehicle_jeep.cpp
        ${SE_SRC_PATH}/game/client/c_vguiscreen.cpp
        ${SE_SRC_PATH}/game/client/hl2/c_waterbullet.cpp
        ${SE_SRC_PATH}/game/client/hl2/hud_autoaim.cpp
        ${SE_SRC_PATH}/game/client/C_WaterLODControl.cpp
        ${SE_SRC_PATH}/game/client/c_world.cpp
        ${SE_SRC_PATH}/game/shared/cam_thirdperson.cpp
        ${SE_SRC_PATH}/game/client/camomaterialproxy.cpp
        ${SE_SRC_PATH}/game/client/cdll_client_int.cpp
        ${SE_SRC_PATH}/game/client/cdll_bounded_cvars.cpp
        ${SE_SRC_PATH}/game/client/cdll_util.cpp
        ${SE_SRC_PATH}/game/client/cl_mat_stub.cpp
        ${SE_SRC_PATH}/game/client/classmap.cpp
        ${SE_SRC_PATH}/game/client/client_factorylist.cpp
        ${SE_SRC_PATH}/game/client/client_thinklist.cpp
        ${SE_SRC_PATH}/game/client/client_virtualreality.cpp
        ${SE_SRC_PATH}/game/client/clienteffectprecachesystem.cpp
        ${SE_SRC_PATH}/game/client/cliententitylist.cpp
        ${SE_SRC_PATH}/game/client/clientleafsystem.cpp
        ${SE_SRC_PATH}/game/client/clientmode_shared.cpp
        ${SE_SRC_PATH}/game/client/clientshadowmgr.cpp
        ${SE_SRC_PATH}/game/client/clientsideeffects.cpp
        ${SE_SRC_PATH}/game/client/clientsideeffects_test.cpp
        ${SE_SRC_PATH}/game/client/clientsteamcontext.cpp
        ${SE_SRC_PATH}/game/client/colorcorrectionmgr.cpp
        ${SE_SRC_PATH}/game/client/commentary_modelviewer.cpp
        ${SE_SRC_PATH}/game/shared/collisionproperty.cpp
        ${SE_SRC_PATH}/game/shared/death_pose.cpp
        ${SE_SRC_PATH}/game/shared/debugoverlay_shared.cpp
        ${SE_SRC_PATH}/game/shared/decals.cpp
        ${SE_SRC_PATH}/game/client/detailobjectsystem.cpp
        ${SE_SRC_PATH}/game/client/dummyproxy.cpp
        ${SE_SRC_PATH}/game/shared/effect_dispatch_data.cpp
        ${SE_SRC_PATH}/game/client/EffectsClient.cpp
        ${SE_SRC_PATH}/game/shared/ehandle.cpp
        ${SE_SRC_PATH}/game/shared/entitylist_base.cpp
        ${SE_SRC_PATH}/game/client/entityoriginmaterialproxy.cpp
        ${SE_SRC_PATH}/game/shared/EntityParticleTrail_Shared.cpp
        ${SE_SRC_PATH}/game/shared/env_detail_controller.cpp
        ${SE_SRC_PATH}/game/shared/env_wind_shared.cpp
        ${SE_SRC_PATH}/game/shared/eventlist.cpp
        ${SE_SRC_PATH}/game/client/flashlighteffect.cpp
        ${SE_SRC_PATH}/game/shared/func_ladder.cpp
        ${SE_SRC_PATH}/game/client/functionproxy.cpp
        ${SE_SRC_PATH}/game/client/fx_blood.cpp
        ${SE_SRC_PATH}/game/client/fx_cube.cpp
        ${SE_SRC_PATH}/game/client/fx_explosion.cpp
        ${SE_SRC_PATH}/game/client/fx_fleck.cpp
        ${SE_SRC_PATH}/game/client/fx_impact.cpp
        ${SE_SRC_PATH}/game/client/fx_interpvalue.cpp
        ${SE_SRC_PATH}/game/client/fx_quad.cpp
        ${SE_SRC_PATH}/game/client/fx_shelleject.cpp
        ${SE_SRC_PATH}/game/client/fx_staticline.cpp
        ${SE_SRC_PATH}/game/client/fx_tracer.cpp
        ${SE_SRC_PATH}/game/client/fx_trail.cpp
        ${SE_SRC_PATH}/game/client/fx_water.cpp
        ${SE_SRC_PATH}/game/shared/gamemovement.cpp
        ${SE_SRC_PATH}/game/shared/gamerules.cpp
        ${SE_SRC_PATH}/game/shared/gamerules_register.cpp
        ${SE_SRC_PATH}/game/shared/GameStats.cpp
        ${SE_SRC_PATH}/game/shared/gamestringpool.cpp
        ${SE_SRC_PATH}/game/client/gametrace_client.cpp
        ${SE_SRC_PATH}/game/shared/gamevars_shared.cpp
        ${SE_SRC_PATH}/game/client/glow_outline_effect.cpp
        ${SE_SRC_PATH}/game/client/glow_overlay.cpp
        ${SE_SRC_PATH}/game/shared/hintmessage.cpp
        ${SE_SRC_PATH}/game/shared/hintsystem.cpp
        ${SE_SRC_PATH}/game/client/hltvcamera.cpp
        ${SE_SRC_PATH}/game/client/hud.cpp
        ${SE_SRC_PATH}/game/client/hud_animationinfo.cpp
        ${SE_SRC_PATH}/game/client/hud_basechat.cpp
        ${SE_SRC_PATH}/game/client/hud_basetimer.cpp
        ${SE_SRC_PATH}/game/client/hud_bitmapnumericdisplay.cpp
        ${SE_SRC_PATH}/game/client/hud_closecaption.cpp
        ${SE_SRC_PATH}/game/client/hud_crosshair.cpp
        ${SE_SRC_PATH}/game/client/hud_element_helper.cpp
        ${SE_SRC_PATH}/game/client/hl2/hud_filmdemo.cpp
        ${SE_SRC_PATH}/game/client/hl2/hud_hdrdemo.cpp
        ${SE_SRC_PATH}/game/client/hud_hintdisplay.cpp
        ${SE_SRC_PATH}/game/client/hud_msg.cpp
        ${SE_SRC_PATH}/game/client/hud_numericdisplay.cpp
        ${SE_SRC_PATH}/game/client/hud_pdump.cpp
        ${SE_SRC_PATH}/game/client/hud_redraw.cpp
        ${SE_SRC_PATH}/game/client/hud_vehicle.cpp
        ${SE_SRC_PATH}/game/shared/igamesystem.cpp
        ${SE_SRC_PATH}/game/client/in_camera.cpp
        ${SE_SRC_PATH}/game/client/in_joystick.cpp
        ${SE_SRC_PATH}/game/client/in_main.cpp
        ${SE_SRC_PATH}/game/client/in_steamcontroller.cpp
        ${SE_SRC_PATH}/game/client/initializer.cpp
        ${SE_SRC_PATH}/game/client/interpolatedvar.cpp
        ${SE_SRC_PATH}/game/client/IsNPCProxy.cpp
        ${SE_SRC_PATH}/game/client/lampbeamproxy.cpp
        ${SE_SRC_PATH}/game/client/lamphaloproxy.cpp
        ${SE_SRC_PATH}/game/shared/mapentities_shared.cpp
        ${SE_SRC_PATH}/game/client/mathproxy.cpp
        ${SE_SRC_PATH}/game/client/matrixproxy.cpp
        ${SE_SRC_PATH}/game/client/menu.cpp
        ${SE_SRC_PATH}/game/client/message.cpp
        ${SE_SRC_PATH}/game/client/movehelper_client.cpp
        ${SE_SRC_PATH}/game/shared/movevars_shared.cpp
        ${SE_SRC_PATH}/game/shared/multiplay_gamerules.cpp
        ${SE_SRC_PATH}/game/shared/obstacle_pushaway.cpp
        ${SE_SRC_PATH}/game/client/panelmetaclassmgr.cpp
        ${SE_SRC_PATH}/game/client/particle_collision.cpp
        ${SE_SRC_PATH}/game/client/particle_litsmokeemitter.cpp
        ${SE_SRC_PATH}/game/shared/particle_parse.cpp
        ${SE_SRC_PATH}/game/shared/particle_property.cpp
        ${SE_SRC_PATH}/game/client/particle_proxies.cpp
        ${SE_SRC_PATH}/game/client/particle_simple3d.cpp
        ${SE_SRC_PATH}/game/client/particlemgr.cpp
        ${SE_SRC_PATH}/game/client/particles_attractor.cpp
        ${SE_SRC_PATH}/game/client/particles_ez.cpp
        ${SE_SRC_PATH}/game/client/particles_localspace.cpp
        ${SE_SRC_PATH}/game/client/particles_new.cpp
        ${SE_SRC_PATH}/game/client/particles_simple.cpp
        ${SE_SRC_PATH}/game/shared/particlesystemquery.cpp
        ${SE_SRC_PATH}/game/client/perfvisualbenchmark.cpp
        ${SE_SRC_PATH}/game/client/physics.cpp
        ${SE_SRC_PATH}/game/client/physics_main_client.cpp
        ${SE_SRC_PATH}/game/shared/physics_main_shared.cpp
        ${SE_SRC_PATH}/game/shared/physics_saverestore.cpp
        ${SE_SRC_PATH}/game/shared/physics_shared.cpp
        ${SE_SRC_PATH}/game/client/physpropclientside.cpp
        ${SE_SRC_PATH}/game/client/playerandobjectenumerator.cpp
        ${SE_SRC_PATH}/game/client/playerspawncache.cpp
        ${SE_SRC_PATH}/game/shared/point_bonusmaps_accessor.cpp
        ${SE_SRC_PATH}/game/shared/point_posecontroller.cpp
        ${SE_SRC_PATH}/game/shared/precache_register.cpp
        ${SE_SRC_PATH}/game/shared/predictableid.cpp
        ${SE_SRC_PATH}/game/client/prediction.cpp
        ${SE_SRC_PATH}/game/shared/predictioncopy.cpp
        ${SE_SRC_PATH}/game/shared/props_shared.cpp
        ${SE_SRC_PATH}/game/client/proxyentity.cpp
        ${SE_SRC_PATH}/game/client/ProxyHealth.cpp
        ${SE_SRC_PATH}/game/client/proxyplayer.cpp
        ${SE_SRC_PATH}/game/client/proxypupil.cpp
        ${SE_SRC_PATH}/game/client/ragdoll.cpp
        ${SE_SRC_PATH}/game/shared/ragdoll_shared.cpp
        ${SE_SRC_PATH}/game/client/recvproxy.cpp
        ${SE_SRC_PATH}/game/client/basepresence.cpp
        ${SE_SRC_PATH}/game/shared/rope_helpers.cpp
        ${SE_SRC_PATH}/game/shared/saverestore.cpp
        ${SE_SRC_PATH}/game/shared/sceneentity_shared.cpp
        ${SE_SRC_PATH}/game/client/ScreenSpaceEffects.cpp
        ${SE_SRC_PATH}/game/shared/sequence_Transitioner.cpp
        ${SE_SRC_PATH}/game/client/simple_keys.cpp
        ${SE_SRC_PATH}/game/shared/simtimer.cpp
        ${SE_SRC_PATH}/game/shared/singleplay_gamerules.cpp
        ${SE_SRC_PATH}/game/shared/SoundEmitterSystem.cpp
        ${SE_SRC_PATH}/game/shared/soundenvelope.cpp
        ${SE_SRC_PATH}/public/SoundParametersInternal.cpp
        ${SE_SRC_PATH}/game/client/splinepatch.cpp
        ${SE_SRC_PATH}/game/shared/Sprite.cpp
        ${SE_SRC_PATH}/game/client/spritemodel.cpp
        ${SE_SRC_PATH}/game/shared/SpriteTrail.cpp
        ${SE_SRC_PATH}/game/shared/studio_shared.cpp
        ${SE_SRC_PATH}/game/client/studio_stats.cpp
        ${SE_SRC_PATH}/game/shared/takedamageinfo.cpp
        ${SE_SRC_PATH}/game/shared/teamplay_gamerules.cpp
        ${SE_SRC_PATH}/game/shared/teamplayroundbased_gamerules.cpp
        ${SE_SRC_PATH}/game/shared/test_ehandle.cpp
        ${SE_SRC_PATH}/game/client/text_message.cpp
        ${SE_SRC_PATH}/game/client/texturescrollmaterialproxy.cpp
        ${SE_SRC_PATH}/game/client/timematerialproxy.cpp
        ${SE_SRC_PATH}/game/client/toggletextureproxy.cpp
        ${SE_SRC_PATH}/game/shared/usercmd.cpp
        ${SE_SRC_PATH}/game/shared/usermessages.cpp
        ${SE_SRC_PATH}/game/shared/util_shared.cpp
        ${SE_SRC_PATH}/game/shared/vehicle_viewblend_shared.cpp
        ${SE_SRC_PATH}/game/client/vgui_avatarimage.cpp
        ${SE_SRC_PATH}/game/client/vgui_basepanel.cpp
        ${SE_SRC_PATH}/game/client/vgui_bitmapbutton.cpp
        ${SE_SRC_PATH}/game/client/vgui_bitmapimage.cpp
        ${SE_SRC_PATH}/game/client/vgui_bitmappanel.cpp
        ${SE_SRC_PATH}/game/client/vgui_schemevisualizer.cpp
        ${SE_SRC_PATH}/game/client/vgui_centerstringpanel.cpp
        ${SE_SRC_PATH}/game/client/vgui_consolepanel.cpp
        ${SE_SRC_PATH}/game/client/vgui_debugoverlaypanel.cpp
        ${SE_SRC_PATH}/game/client/vgui_fpspanel.cpp
        ${SE_SRC_PATH}/game/client/vgui_game_viewport.cpp
        ${SE_SRC_PATH}/game/client/vgui_grid.cpp
        ${SE_SRC_PATH}/game/client/vgui_int.cpp
        ${SE_SRC_PATH}/game/client/vgui_loadingdiscpanel.cpp
        ${SE_SRC_PATH}/game/client/vgui_messagechars.cpp
        ${SE_SRC_PATH}/game/client/vgui_netgraphpanel.cpp
        ${SE_SRC_PATH}/game/client/vgui_slideshow_display_screen.cpp
        ${SE_SRC_PATH}/game/client/view.cpp
        ${SE_SRC_PATH}/game/client/view_beams.cpp
        ${SE_SRC_PATH}/game/client/view_effects.cpp
        ${SE_SRC_PATH}/game/client/view_scene.cpp
        ${SE_SRC_PATH}/game/client/viewangleanim.cpp
        ${SE_SRC_PATH}/game/client/ViewConeImage.cpp
        ${SE_SRC_PATH}/game/client/viewdebug.cpp
        ${SE_SRC_PATH}/game/client/viewpostprocess.cpp
        ${SE_SRC_PATH}/game/client/viewrender.cpp
        ${SE_SRC_PATH}/game/shared/voice_banmgr.cpp
        ${SE_SRC_PATH}/game/shared/voice_status.cpp
        ${SE_SRC_PATH}/game/client/warp_overlay.cpp
        ${SE_SRC_PATH}/game/client/WaterLODMaterialProxy.cpp
        ${SE_SRC_PATH}/game/shared/weapon_parse.cpp
        ${SE_SRC_PATH}/game/client/weapon_selection.cpp
        ${SE_SRC_PATH}/game/client/weapons_resource.cpp
        ${SE_SRC_PATH}/game/client/WorldDimsProxy.cpp
        ${SE_SRC_PATH}/game/client/vgui_video.cpp
        ${SE_SRC_PATH}/game/client/vgui_video_player.cpp
        ${SE_SRC_PATH}/game/shared/mp_shareddefs.cpp
        ${SE_SRC_PATH}/game/client/c_vote_controller.cpp
        ${SE_SRC_PATH}/game/client/sixense/in_sixense.cpp
        ${SE_SRC_PATH}/game/client/sixense/in_sixense_gesture_bindings.cpp
        ${SE_SRC_PATH}/game/shared/sixense/sixense_convars.cpp
        ${SE_SRC_PATH}/public/bone_setup.cpp
        ${SE_SRC_PATH}/public/posedebugger.cpp
        ${SE_SRC_PATH}/public/client_class.cpp
        ${SE_SRC_PATH}/common/compiledcaptionswap.cpp
        ${SE_SRC_PATH}/public/collisionutils.cpp
        ${SE_SRC_PATH}/public/crtmemdebug.cpp
        ${SE_SRC_PATH}/public/dt_recv.cpp
        ${SE_SRC_PATH}/public/dt_utlvector_common.cpp
        ${SE_SRC_PATH}/public/dt_utlvector_recv.cpp
        ${SE_SRC_PATH}/public/filesystem_helpers.cpp
        ${SE_SRC_PATH}/public/interpolatortypes.cpp
        ${SE_SRC_PATH}/game/shared/interval.cpp
        ${SE_SRC_PATH}/common/language.cpp
        ${SE_SRC_PATH}/public/networkvar.cpp
        ${SE_SRC_PATH}/common/randoverride.cpp
        ${SE_SRC_PATH}/common/steamid.cpp
        ${SE_SRC_PATH}/public/rope_physics.cpp
        ${SE_SRC_PATH}/public/scratchpad3d.cpp
        ${SE_SRC_PATH}/public/ScratchPadUtils.cpp
        ${SE_SRC_PATH}/public/sentence.cpp
        ${SE_SRC_PATH}/game/shared/sheetsimulator.cpp
        ${SE_SRC_PATH}/public/simple_physics.cpp
        ${SE_SRC_PATH}/public/stringregistry.cpp
        ${SE_SRC_PATH}/public/studio.cpp
        ${SE_SRC_PATH}/public/vallocator.cpp
        ${SE_SRC_PATH}/public/vgui_controls/vgui_controls.cpp
        ${SE_SRC_PATH}/public/jigglebones.cpp
        ${SE_SRC_PATH}/game/client/hud_lcd.cpp
        ${SE_SRC_PATH}/game/client/in_mouse.cpp
        ${SE_SRC_PATH}/game/client/mumble.cpp
        ${SE_SRC_PATH}/public/renamed_recvtable_compat.cpp
        ${SE_SRC_PATH}/game/client/rendertexture.cpp
        ${SE_SRC_PATH}/game/client/c_basetempentity.cpp
        ${SE_SRC_PATH}/game/client/c_effects.cpp
        ${SE_SRC_PATH}/game/client/c_impact_effects.cpp
        ${SE_SRC_PATH}/game/client/c_movie_explosion.cpp
        ${SE_SRC_PATH}/game/client/c_particle_fire.cpp
        ${SE_SRC_PATH}/game/client/c_particle_smokegrenade.cpp
        ${SE_SRC_PATH}/game/client/c_prop_vehicle.cpp
        ${SE_SRC_PATH}/game/client/c_recipientfilter.cpp
        ${SE_SRC_PATH}/game/client/c_smoke_trail.cpp
        ${SE_SRC_PATH}/game/client/c_smokestack.cpp
        ${SE_SRC_PATH}/game/client/c_steamjet.cpp
        ${SE_SRC_PATH}/game/client/c_stickybolt.cpp
        ${SE_SRC_PATH}/game/client/c_te.cpp
        ${SE_SRC_PATH}/game/client/c_te_armorricochet.cpp
        ${SE_SRC_PATH}/game/client/c_te_basebeam.cpp
        ${SE_SRC_PATH}/game/client/c_te_beamentpoint.cpp
        ${SE_SRC_PATH}/game/client/c_te_beaments.cpp
        ${SE_SRC_PATH}/game/client/c_te_beamfollow.cpp
        ${SE_SRC_PATH}/game/client/c_te_beamlaser.cpp
        ${SE_SRC_PATH}/game/client/c_te_beampoints.cpp
        ${SE_SRC_PATH}/game/client/c_te_beamring.cpp
        ${SE_SRC_PATH}/game/client/c_te_beamringpoint.cpp
        ${SE_SRC_PATH}/game/client/c_te_beamspline.cpp
        ${SE_SRC_PATH}/game/client/c_te_bloodsprite.cpp
        ${SE_SRC_PATH}/game/client/c_te_bloodstream.cpp
        ${SE_SRC_PATH}/game/client/c_te_breakmodel.cpp
        ${SE_SRC_PATH}/game/client/c_te_bspdecal.cpp
        ${SE_SRC_PATH}/game/client/c_te_bubbles.cpp
        ${SE_SRC_PATH}/game/client/c_te_bubbletrail.cpp
        ${SE_SRC_PATH}/game/client/c_te_clientprojectile.cpp
        ${SE_SRC_PATH}/game/client/c_te_decal.cpp
        ${SE_SRC_PATH}/game/client/c_te_dynamiclight.cpp
        ${SE_SRC_PATH}/game/client/c_te_effect_dispatch.cpp
        ${SE_SRC_PATH}/game/client/c_te_energysplash.cpp
        ${SE_SRC_PATH}/game/client/c_te_explosion.cpp
        ${SE_SRC_PATH}/game/client/c_te_fizz.cpp
        ${SE_SRC_PATH}/game/client/c_te_footprint.cpp
        ${SE_SRC_PATH}/game/client/c_te_glassshatter.cpp
        ${SE_SRC_PATH}/game/client/c_te_glowsprite.cpp
        ${SE_SRC_PATH}/game/client/c_te_impact.cpp
        ${SE_SRC_PATH}/game/client/c_te_killplayerattachments.cpp
        ${SE_SRC_PATH}/game/client/c_te_largefunnel.cpp
        ${SE_SRC_PATH}/game/client/c_te_legacytempents.cpp
        ${SE_SRC_PATH}/game/client/c_te_muzzleflash.cpp
        ${SE_SRC_PATH}/game/client/c_te_particlesystem.cpp
        ${SE_SRC_PATH}/game/client/c_te_physicsprop.cpp
        ${SE_SRC_PATH}/game/client/c_te_playerdecal.cpp
        ${SE_SRC_PATH}/game/client/c_te_projecteddecal.cpp
        ${SE_SRC_PATH}/game/client/c_te_showline.cpp
        ${SE_SRC_PATH}/game/client/c_te_smoke.cpp
        ${SE_SRC_PATH}/game/client/c_te_sparks.cpp
        ${SE_SRC_PATH}/game/client/c_te_sprite.cpp
        ${SE_SRC_PATH}/game/client/c_te_spritespray.cpp
        ${SE_SRC_PATH}/game/client/c_te_worlddecal.cpp
        ${SE_SRC_PATH}/game/client/c_testtraceline.cpp
        ${SE_SRC_PATH}/game/client/c_tracer.cpp
        ${SE_SRC_PATH}/game/client/fx.cpp
        ${SE_SRC_PATH}/game/client/fx_discreetline.cpp
        ${SE_SRC_PATH}/game/client/fx_envelope.cpp
        ${SE_SRC_PATH}/game/client/fx_line.cpp
        ${SE_SRC_PATH}/game/client/fx_sparks.cpp
        ${SE_SRC_PATH}/game/client/particlesphererenderer.cpp
        ${SE_SRC_PATH}/game/client/smoke_fog_overlay.cpp
        ${SE_SRC_PATH}/game/client/game_controls/baseviewport.cpp
        ${SE_SRC_PATH}/game/client/game_controls/basemodelpanel.cpp
        ${SE_SRC_PATH}/game/client/game_controls/basemodel_panel.cpp
        ${SE_SRC_PATH}/game/client/game_controls/ClientScoreBoardDialog.cpp
        ${SE_SRC_PATH}/game/client/game_controls/commandmenu.cpp
        ${SE_SRC_PATH}/game/client/game_controls/intromenu.cpp
        ${SE_SRC_PATH}/game/client/game_controls/MapOverview.cpp
        ${SE_SRC_PATH}/game/client/game_controls/NavProgress.cpp
        ${SE_SRC_PATH}/game/client/game_controls/SpectatorGUI.cpp
        ${SE_SRC_PATH}/game/client/game_controls/teammenu.cpp
        ${SE_SRC_PATH}/game/client/game_controls/vguitextwindow.cpp
        ${SE_SRC_PATH}/game/client/game_controls/IconPanel.cpp
        ${SE_SRC_PATH}/game/client/mp3player.cpp
        ${SE_SRC_PATH}/public/tools/bonelist.cpp
        ${SE_SRC_PATH}/game/client/entity_client_tools.cpp
        ${SE_SRC_PATH}/game/client/toolframework_client.cpp
        ${SE_SRC_PATH}/public/haptics/haptic_msgs.cpp

        ${SE_SRC_PATH}/game/client/touch.cpp
        )
if(SE_WIN32)
    target_sources(client_base INTERFACE
        ${SE_SRC_PATH}/public/haptics/haptic_utils.cpp
    )
endif()
target_include_directories(client_base INTERFACE
        ${SE_SRC_PATH}/game/client
        ${SE_SRC_PATH}/public
        ${SE_SRC_PATH}/public/tier0
        ${SE_SRC_PATH}/public/tier1
        ${SE_SRC_PATH}/common

        ${SE_SRC_PATH}/public
        ${SE_SRC_PATH}/vgui2/vgui_controls
        ${SE_SRC_PATH}/game/shared
        ${SE_SRC_PATH}/game/client/game_controls
        )
target_compile_definitions(client_base INTERFACE NO_STRING_T CLIENT_DLL VECTOR VERSION_SAFE_STEAM_API_INTERFACES PROTECTED_THINGS_ENABLE strncpy=use_Q_strncpy_instead _snprintf=use_Q_snprintf_instead)
if(SE_WIN32)
    target_compile_definitions(client_base INTERFACE fopen=dont_use_fopen)
endif()
target_compile_definitions(client_base INTERFACE USE_WEBM_FOR_REPLAY)
target_link_libraries(client_base INTERFACE platform_config video_config bitmap choreoobjects dmxloader mathlib matsys_controls particles tier1 tier2 tier3 vgui_controls vtf steam_api)

add_library(client_relay INTERFACE)
target_sources(client_relay INTERFACE
        ${SE_SRC_PATH}/game/client/replay/gamedefs.h
        ${SE_SRC_PATH}/game/client/replay/gamedefs.cpp
        ${SE_SRC_PATH}/game/client/replay/replay_ragdoll.cpp
        ${SE_SRC_PATH}/game/client/replay/replay_ragdoll.h
        ${SE_SRC_PATH}/game/client/replay/replay_screenshot.cpp
        ${SE_SRC_PATH}/game/client/replay/replay_screenshot.h
        ${SE_SRC_PATH}/game/client/replay/replayperformanceplaybackhandler.h
        ${SE_SRC_PATH}/game/client/replay/replayperformanceplaybackhandler.cpp
        ${SE_SRC_PATH}/game/client/replay/replayrenderer.cpp
        ${SE_SRC_PATH}/game/client/replay/replayrenderer.h
        ${SE_SRC_PATH}/game/client/replay/replayvideo.cpp
        ${SE_SRC_PATH}/game/client/replay/replayvideo.h
        ${SE_SRC_PATH}/game/client/replay/genericclassbased_replay.cpp
        ${SE_SRC_PATH}/game/client/replay/genericclassbased_replay.h
        ${SE_SRC_PATH}/game/shared/replay_gamestats_shared.cpp
        ${SE_SRC_PATH}/game/shared/replay_gamestats_shared.h
        ${SE_SRC_PATH}/game/client/youtubeapi.h
        ${SE_SRC_PATH}/game/client/youtubeapi.cpp

        ${SE_SRC_PATH}/game/client/replay/vgui/replaybrowserbasepage.cpp
        ${SE_SRC_PATH}/game/client/replay/vgui/replaybrowserbasepage.h
        ${SE_SRC_PATH}/game/client/replay/vgui/replaybrowserbasepanel.cpp
        ${SE_SRC_PATH}/game/client/replay/vgui/replaybrowserbasepanel.h
        ${SE_SRC_PATH}/game/client/replay/vgui/replayconfirmquitdlg.cpp
        ${SE_SRC_PATH}/game/client/replay/vgui/replayconfirmquitdlg.h
        ${SE_SRC_PATH}/game/client/replay/vgui/replaybrowserdetailspanel.cpp
        ${SE_SRC_PATH}/game/client/replay/vgui/replaybrowserdetailspanel.h
        ${SE_SRC_PATH}/game/client/replay/vgui/replaybrowseritemmanager.cpp
        ${SE_SRC_PATH}/game/client/replay/vgui/replaybrowseritemmanager.h
        ${SE_SRC_PATH}/game/client/replay/vgui/replaybrowserlistitempanel.cpp
        ${SE_SRC_PATH}/game/client/replay/vgui/replaybrowserlistitempanel.h
        ${SE_SRC_PATH}/game/client/replay/vgui/replaybrowserlistpanel.cpp
        ${SE_SRC_PATH}/game/client/replay/vgui/replaybrowserlistpanel.h
        ${SE_SRC_PATH}/game/client/replay/vgui/replaybrowsermainpanel.cpp
        ${SE_SRC_PATH}/game/client/replay/vgui/replaybrowsermainpanel.h
        ${SE_SRC_PATH}/game/client/replay/vgui/replaybrowsermovieplayerpanel.cpp
        ${SE_SRC_PATH}/game/client/replay/vgui/replaybrowsermovieplayerpanel.h
        ${SE_SRC_PATH}/game/client/replay/vgui/replaybrowserpreviewpanel.cpp
        ${SE_SRC_PATH}/game/client/replay/vgui/replaybrowserpreviewpanel.h
        ${SE_SRC_PATH}/game/client/replay/vgui/replaybrowserrenderdialog.cpp
        ${SE_SRC_PATH}/game/client/replay/vgui/replaybrowserrenderdialog.h
        ${SE_SRC_PATH}/game/client/replay/vgui/replayinputpanel.cpp
        ${SE_SRC_PATH}/game/client/replay/vgui/replayinputpanel.h
        ${SE_SRC_PATH}/game/client/replay/vgui/replaymessagepanel.cpp
        ${SE_SRC_PATH}/game/client/replay/vgui/replaymessagepanel.h
        ${SE_SRC_PATH}/game/client/replay/vgui/replayperformanceeditor.cpp
        ${SE_SRC_PATH}/game/client/replay/vgui/replayperformanceeditor.h
        ${SE_SRC_PATH}/game/client/replay/vgui/replayperformancesavedlg.cpp
        ${SE_SRC_PATH}/game/client/replay/vgui/replayperformancesavedlg.h
        ${SE_SRC_PATH}/game/client/replay/vgui/replayrenderoverlay.cpp
        ${SE_SRC_PATH}/game/client/replay/vgui/replayrenderoverlay.h
        ${SE_SRC_PATH}/game/client/replay/vgui/replayreminderpanel.cpp
        ${SE_SRC_PATH}/game/client/replay/vgui/replayreminderpanel.h
        ${SE_SRC_PATH}/game/client/replay/replayyoutubeapi.cpp
        ${SE_SRC_PATH}/game/client/replay/replayyoutubeapi.h
        ${SE_SRC_PATH}/game/client/replay/replayyoutubeapi_key.cpp #[!$SOURCESDK]
        ${SE_SRC_PATH}/game/client/replay/replayyoutubeapi_key_sdk.cpp #[$SOURCESDK]
        ${SE_SRC_PATH}/game/client/game_controls/slideshowpanel.cpp
        ${SE_SRC_PATH}/game/client/game_controls/slideshowpanel.h
        
)

add_library(server_base INTERFACE)
target_sources(server_base INTERFACE
        ${SE_SRC_PATH}/common/replay/ireplaysessionrecorder.h
        ${SE_SRC_PATH}/game/shared/achievement_saverestore.cpp
        ${SE_SRC_PATH}/game/shared/achievement_saverestore.h
        ${SE_SRC_PATH}/game/shared/achievementmgr.cpp
        ${SE_SRC_PATH}/game/shared/achievementmgr.h
        ${SE_SRC_PATH}/game/shared/achievements_hlx.cpp
        ${SE_SRC_PATH}/game/shared/activitylist.cpp
        ${SE_SRC_PATH}/game/shared/activitylist.h
        ${SE_SRC_PATH}/game/server/ai_activity.cpp
        ${SE_SRC_PATH}/game/shared/ai_activity.h
        ${SE_SRC_PATH}/game/server/ai_baseactor.cpp
        ${SE_SRC_PATH}/game/server/ai_baseactor.h
        ${SE_SRC_PATH}/game/server/ai_basehumanoid.cpp
        ${SE_SRC_PATH}/game/server/ai_basehumanoid.h
        ${SE_SRC_PATH}/game/server/ai_basenpc.cpp
        ${SE_SRC_PATH}/game/server/ai_basenpc.h
        ${SE_SRC_PATH}/game/server/ai_basenpc_flyer.cpp
        ${SE_SRC_PATH}/game/server/ai_basenpc_flyer.h
        ${SE_SRC_PATH}/game/server/ai_basenpc_flyer_new.cpp
        ${SE_SRC_PATH}/game/server/ai_basenpc_flyer_new.h
        ${SE_SRC_PATH}/game/server/ai_basenpc_movement.cpp
        ${SE_SRC_PATH}/game/server/ai_basenpc_physicsflyer.cpp
        ${SE_SRC_PATH}/game/server/ai_basenpc_physicsflyer.h
        ${SE_SRC_PATH}/game/server/ai_basenpc_schedule.cpp
        ${SE_SRC_PATH}/game/server/ai_basenpc_squad.cpp
        ${SE_SRC_PATH}/game/server/ai_behavior.cpp
        ${SE_SRC_PATH}/game/server/ai_behavior.h
        ${SE_SRC_PATH}/game/server/ai_behavior_assault.cpp
        ${SE_SRC_PATH}/game/server/ai_behavior_assault.h
        ${SE_SRC_PATH}/game/server/ai_behavior_fear.cpp
        ${SE_SRC_PATH}/game/server/ai_behavior_fear.h
        ${SE_SRC_PATH}/game/server/ai_behavior_follow.cpp
        ${SE_SRC_PATH}/game/server/ai_behavior_follow.h
        ${SE_SRC_PATH}/game/server/ai_behavior_lead.cpp
        ${SE_SRC_PATH}/game/server/ai_behavior_lead.h
        ${SE_SRC_PATH}/game/server/ai_behavior_rappel.cpp
        ${SE_SRC_PATH}/game/server/ai_behavior_rappel.h
        ${SE_SRC_PATH}/game/server/ai_behavior_standoff.cpp
        ${SE_SRC_PATH}/game/server/ai_behavior_standoff.h
        ${SE_SRC_PATH}/game/server/ai_blended_movement.cpp
        ${SE_SRC_PATH}/game/server/ai_blended_movement.h
        ${SE_SRC_PATH}/game/server/ai_component.h
        ${SE_SRC_PATH}/game/server/ai_concommands.cpp
        ${SE_SRC_PATH}/game/server/ai_condition.cpp
        ${SE_SRC_PATH}/game/server/ai_condition.h
        ${SE_SRC_PATH}/game/server/AI_Criteria.cpp
        ${SE_SRC_PATH}/game/server/AI_Criteria.h
        ${SE_SRC_PATH}/game/server/ai_debug.h
        ${SE_SRC_PATH}/game/shared/ai_debug_shared.h
        ${SE_SRC_PATH}/game/server/ai_default.cpp
        ${SE_SRC_PATH}/game/server/ai_default.h
        ${SE_SRC_PATH}/game/server/ai_dynamiclink.cpp
        ${SE_SRC_PATH}/game/server/ai_dynamiclink.h
        ${SE_SRC_PATH}/game/server/ai_event.cpp
        ${SE_SRC_PATH}/game/server/ai_goalentity.cpp
        ${SE_SRC_PATH}/game/server/ai_goalentity.h
        ${SE_SRC_PATH}/game/server/ai_hint.cpp
        ${SE_SRC_PATH}/game/server/ai_hint.h
        ${SE_SRC_PATH}/game/server/ai_hull.cpp
        ${SE_SRC_PATH}/game/server/ai_hull.h
        ${SE_SRC_PATH}/game/server/ai_initutils.cpp
        ${SE_SRC_PATH}/game/server/ai_initutils.h
        ${SE_SRC_PATH}/game/server/AI_Interest_Target.cpp
        ${SE_SRC_PATH}/game/server/AI_Interest_Target.h
        ${SE_SRC_PATH}/game/server/ai_link.cpp
        ${SE_SRC_PATH}/game/server/ai_link.h
        ${SE_SRC_PATH}/game/server/ai_localnavigator.cpp
        ${SE_SRC_PATH}/game/server/ai_localnavigator.h
        ${SE_SRC_PATH}/game/server/ai_looktarget.cpp
        ${SE_SRC_PATH}/game/server/ai_looktarget.h
        ${SE_SRC_PATH}/game/server/ai_memory.cpp
        ${SE_SRC_PATH}/game/server/ai_memory.h
        ${SE_SRC_PATH}/game/server/ai_motor.cpp
        ${SE_SRC_PATH}/game/server/ai_motor.h
        ${SE_SRC_PATH}/game/server/ai_moveprobe.cpp
        ${SE_SRC_PATH}/game/server/ai_moveprobe.h
        ${SE_SRC_PATH}/game/server/ai_moveshoot.cpp
        ${SE_SRC_PATH}/game/server/ai_moveshoot.h
        ${SE_SRC_PATH}/game/server/ai_movesolver.cpp
        ${SE_SRC_PATH}/game/server/ai_movesolver.h
        ${SE_SRC_PATH}/game/server/ai_movetypes.h
        ${SE_SRC_PATH}/game/server/ai_namespaces.cpp
        ${SE_SRC_PATH}/game/server/ai_namespaces.h
        ${SE_SRC_PATH}/game/server/ai_navgoaltype.h
        ${SE_SRC_PATH}/game/server/ai_navigator.cpp
        ${SE_SRC_PATH}/game/server/ai_navigator.h
        ${SE_SRC_PATH}/game/server/ai_navtype.h
        ${SE_SRC_PATH}/game/server/ai_network.cpp
        ${SE_SRC_PATH}/game/server/ai_network.h
        ${SE_SRC_PATH}/game/server/ai_networkmanager.cpp
        ${SE_SRC_PATH}/game/server/ai_networkmanager.h
        ${SE_SRC_PATH}/game/server/ai_node.cpp
        ${SE_SRC_PATH}/game/server/ai_node.h
        ${SE_SRC_PATH}/game/server/ai_npcstate.h
        ${SE_SRC_PATH}/game/server/ai_obstacle_type.h
        ${SE_SRC_PATH}/game/server/ai_pathfinder.cpp
        ${SE_SRC_PATH}/game/server/ai_pathfinder.h
        ${SE_SRC_PATH}/game/server/ai_planesolver.cpp
        ${SE_SRC_PATH}/game/server/ai_planesolver.h
        ${SE_SRC_PATH}/game/server/ai_playerally.cpp
        ${SE_SRC_PATH}/game/server/ai_playerally.h
        ${SE_SRC_PATH}/game/server/AI_ResponseSystem.cpp
        ${SE_SRC_PATH}/game/server/AI_ResponseSystem.h
        ${SE_SRC_PATH}/game/server/ai_route.cpp
        ${SE_SRC_PATH}/game/server/ai_route.h
        ${SE_SRC_PATH}/game/server/ai_routedist.h
        ${SE_SRC_PATH}/game/server/ai_saverestore.cpp
        ${SE_SRC_PATH}/game/server/ai_saverestore.h
        ${SE_SRC_PATH}/game/server/ai_schedule.cpp
        ${SE_SRC_PATH}/game/server/ai_schedule.h
        ${SE_SRC_PATH}/game/server/ai_scriptconditions.cpp
        ${SE_SRC_PATH}/game/server/ai_scriptconditions.h
        ${SE_SRC_PATH}/game/server/ai_senses.cpp
        ${SE_SRC_PATH}/game/server/ai_senses.h
        ${SE_SRC_PATH}/game/server/ai_sentence.cpp
        ${SE_SRC_PATH}/game/server/ai_sentence.h
        ${SE_SRC_PATH}/game/server/ai_speech.cpp
        ${SE_SRC_PATH}/game/server/ai_speech.h
        ${SE_SRC_PATH}/game/server/ai_speechfilter.cpp
        ${SE_SRC_PATH}/game/server/ai_speechfilter.h
        ${SE_SRC_PATH}/game/server/ai_squad.cpp
        ${SE_SRC_PATH}/game/server/ai_squad.h
        ${SE_SRC_PATH}/game/server/ai_squadslot.cpp
        ${SE_SRC_PATH}/game/server/ai_squadslot.h
        ${SE_SRC_PATH}/game/server/ai_tacticalservices.cpp
        ${SE_SRC_PATH}/game/server/ai_tacticalservices.h
        ${SE_SRC_PATH}/game/server/ai_task.cpp
        ${SE_SRC_PATH}/game/server/ai_task.h
        ${SE_SRC_PATH}/game/server/ai_trackpather.cpp
        ${SE_SRC_PATH}/game/server/ai_trackpather.h
        ${SE_SRC_PATH}/game/server/ai_utils.cpp
        ${SE_SRC_PATH}/game/server/ai_utils.h
        ${SE_SRC_PATH}/game/server/ai_waypoint.cpp
        ${SE_SRC_PATH}/game/server/ai_waypoint.h
        ${SE_SRC_PATH}/game/shared/ammodef.cpp
        ${SE_SRC_PATH}/game/shared/animation.cpp
        ${SE_SRC_PATH}/game/shared/animation.h
        ${SE_SRC_PATH}/game/shared/apparent_velocity_helper.h
        ${SE_SRC_PATH}/game/shared/base_playeranimstate.cpp
        ${SE_SRC_PATH}/game/server/base_transmit_proxy.cpp
        ${SE_SRC_PATH}/game/shared/baseachievement.cpp
        ${SE_SRC_PATH}/game/shared/baseachievement.h
        ${SE_SRC_PATH}/game/server/baseanimating.cpp
        ${SE_SRC_PATH}/game/server/baseanimating.h
        ${SE_SRC_PATH}/game/server/BaseAnimatingOverlay.cpp
        ${SE_SRC_PATH}/game/server/BaseAnimatingOverlay.h
        ${SE_SRC_PATH}/game/server/basecombatcharacter.cpp
        ${SE_SRC_PATH}/game/server/basecombatcharacter.h
        ${SE_SRC_PATH}/game/shared/basecombatcharacter_shared.cpp
        ${SE_SRC_PATH}/game/server/basecombatweapon.cpp
        ${SE_SRC_PATH}/game/server/basecombatweapon.h
        ${SE_SRC_PATH}/game/shared/basecombatweapon_shared.cpp
        ${SE_SRC_PATH}/game/shared/basecombatweapon_shared.h
        ${SE_SRC_PATH}/game/server/baseentity.cpp
        ${SE_SRC_PATH}/game/server/baseentity.h
        ${SE_SRC_PATH}/game/shared/baseentity_shared.cpp
        ${SE_SRC_PATH}/game/shared/baseentity_shared.h
        ${SE_SRC_PATH}/game/server/baseflex.cpp
        ${SE_SRC_PATH}/game/server/baseflex.h
        ${SE_SRC_PATH}/game/shared/basegrenade_shared.cpp
        ${SE_SRC_PATH}/game/shared/basegrenade_shared.h
        ${SE_SRC_PATH}/game/server/basemultiplayerplayer.cpp
        ${SE_SRC_PATH}/game/server/basemultiplayerplayer.h
        ${SE_SRC_PATH}/game/shared/baseparticleentity.cpp
        ${SE_SRC_PATH}/game/shared/baseparticleentity.h
        ${SE_SRC_PATH}/game/shared/baseplayer_shared.cpp
        ${SE_SRC_PATH}/game/shared/baseplayer_shared.h
        ${SE_SRC_PATH}/game/shared/baseprojectile.cpp
        ${SE_SRC_PATH}/game/shared/baseprojectile.h
        ${SE_SRC_PATH}/game/server/BasePropDoor.h
        ${SE_SRC_PATH}/game/server/basetoggle.h
        ${SE_SRC_PATH}/game/server/baseviewmodel.cpp
        ${SE_SRC_PATH}/game/server/baseviewmodel.h
        ${SE_SRC_PATH}/game/shared/baseviewmodel_shared.cpp
        ${SE_SRC_PATH}/game/shared/baseviewmodel_shared.h
        ${SE_SRC_PATH}/game/shared/beam_shared.cpp
        ${SE_SRC_PATH}/game/shared/beam_shared.h
        ${SE_SRC_PATH}/game/server/bitstring.cpp
        ${SE_SRC_PATH}/game/server/bitstring.h
        ${SE_SRC_PATH}/game/server/bmodels.cpp
        ${SE_SRC_PATH}/public/bone_setup.h
        ${SE_SRC_PATH}/game/server/buttons.cpp
        ${SE_SRC_PATH}/game/server/buttons.h
        ${SE_SRC_PATH}/game/server/cbase.cpp
        ${SE_SRC_PATH}/game/server/cbase.h
        ${SE_SRC_PATH}/game/shared/choreoactor.h
        ${SE_SRC_PATH}/game/shared/choreochannel.h
        ${SE_SRC_PATH}/game/shared/choreoevent.h
        ${SE_SRC_PATH}/game/shared/choreoscene.h
        ${SE_SRC_PATH}/game/server/client.cpp
        ${SE_SRC_PATH}/game/server/client.h
        ${SE_SRC_PATH}/game/shared/collisionproperty.cpp
        ${SE_SRC_PATH}/game/shared/collisionproperty.h
        ${SE_SRC_PATH}/public/collisionutils.h
        ${SE_SRC_PATH}/game/server/colorcorrection.cpp
        ${SE_SRC_PATH}/game/server/colorcorrectionvolume.cpp
        ${SE_SRC_PATH}/game/server/CommentarySystem.cpp
        ${SE_SRC_PATH}/game/server/controlentities.cpp
        ${SE_SRC_PATH}/game/server/cplane.cpp
        ${SE_SRC_PATH}/game/server/CRagdollMagnet.cpp
        ${SE_SRC_PATH}/game/server/CRagdollMagnet.h
        ${SE_SRC_PATH}/game/server/damagemodifier.cpp
        ${SE_SRC_PATH}/game/shared/death_pose.cpp
        ${SE_SRC_PATH}/game/shared/debugoverlay_shared.cpp
        ${SE_SRC_PATH}/game/shared/debugoverlay_shared.h
        ${SE_SRC_PATH}/game/shared/decals.cpp
        ${SE_SRC_PATH}/game/server/doors.cpp
        ${SE_SRC_PATH}/game/server/doors.h
        ${SE_SRC_PATH}/game/server/dynamiclight.cpp
        ${SE_SRC_PATH}/public/edict.h
        ${SE_SRC_PATH}/public/editor_sendcommand.h
        ${SE_SRC_PATH}/game/shared/effect_color_tables.h
        ${SE_SRC_PATH}/game/shared/effect_dispatch_data.cpp
        ${SE_SRC_PATH}/game/server/effects.cpp
        ${SE_SRC_PATH}/game/server/effects.h
        ${SE_SRC_PATH}/game/server/EffectsServer.cpp
        ${SE_SRC_PATH}/game/shared/ehandle.cpp
        ${SE_SRC_PATH}/public/eiface.h
        ${SE_SRC_PATH}/game/server/enginecallback.h
        ${SE_SRC_PATH}/game/server/entityapi.h
        ${SE_SRC_PATH}/game/server/entityblocker.cpp
        ${SE_SRC_PATH}/game/server/entityblocker.h
        ${SE_SRC_PATH}/game/server/EntityDissolve.cpp
        ${SE_SRC_PATH}/game/server/EntityDissolve.h
        ${SE_SRC_PATH}/game/server/EntityFlame.cpp
        ${SE_SRC_PATH}/game/server/entityinput.h
        ${SE_SRC_PATH}/game/server/entitylist.cpp
        ${SE_SRC_PATH}/game/server/entitylist.h
        ${SE_SRC_PATH}/game/shared/entitylist_base.cpp
        ${SE_SRC_PATH}/game/server/entityoutput.h
        ${SE_SRC_PATH}/game/server/EntityParticleTrail.cpp
        ${SE_SRC_PATH}/game/server/EntityParticleTrail.h
        ${SE_SRC_PATH}/game/shared/EntityParticleTrail_Shared.cpp
        ${SE_SRC_PATH}/game/shared/entityparticletrail_shared.h
        ${SE_SRC_PATH}/game/server/env_debughistory.cpp
        ${SE_SRC_PATH}/game/server/env_debughistory.h
        ${SE_SRC_PATH}/game/shared/env_detail_controller.cpp
        ${SE_SRC_PATH}/game/server/env_effectsscript.cpp
        ${SE_SRC_PATH}/game/server/env_entity_maker.cpp
        ${SE_SRC_PATH}/game/server/env_particlescript.cpp
        ${SE_SRC_PATH}/game/server/env_player_surface_trigger.cpp
        ${SE_SRC_PATH}/game/server/env_player_surface_trigger.h
        ${SE_SRC_PATH}/game/server/env_projectedtexture.cpp
        ${SE_SRC_PATH}/game/server/env_screenoverlay.cpp
        ${SE_SRC_PATH}/game/server/env_texturetoggle.cpp
        ${SE_SRC_PATH}/game/server/env_tonemap_controller.cpp
        ${SE_SRC_PATH}/game/shared/env_wind_shared.cpp
        ${SE_SRC_PATH}/game/shared/env_wind_shared.h
        ${SE_SRC_PATH}/game/server/env_zoom.cpp
        ${SE_SRC_PATH}/game/server/env_zoom.h
        ${SE_SRC_PATH}/game/server/EnvBeam.cpp
        ${SE_SRC_PATH}/game/server/EnvFade.cpp
        ${SE_SRC_PATH}/game/server/EnvHudHint.cpp
        ${SE_SRC_PATH}/game/server/EnvLaser.cpp
        ${SE_SRC_PATH}/game/server/EnvLaser.h
        ${SE_SRC_PATH}/game/server/EnvMessage.cpp
        ${SE_SRC_PATH}/game/server/EnvMessage.h
        ${SE_SRC_PATH}/game/server/envmicrophone.cpp
        ${SE_SRC_PATH}/game/server/envmicrophone.h
        ${SE_SRC_PATH}/game/server/EnvShake.cpp
        ${SE_SRC_PATH}/game/server/EnvSpark.cpp
        ${SE_SRC_PATH}/game/server/envspark.h
        ${SE_SRC_PATH}/public/event_flags.h
        ${SE_SRC_PATH}/game/server/event_tempentity_tester.h
        ${SE_SRC_PATH}/game/shared/eventlist.cpp
        ${SE_SRC_PATH}/game/shared/eventlist.h
        ${SE_SRC_PATH}/game/server/EventLog.cpp
        ${SE_SRC_PATH}/game/server/eventqueue.h
        ${SE_SRC_PATH}/game/server/explode.cpp
        ${SE_SRC_PATH}/game/server/explode.h
        ${SE_SRC_PATH}/game/server/filters.cpp
        ${SE_SRC_PATH}/game/server/filters.h
        ${SE_SRC_PATH}/game/server/fire.cpp
        ${SE_SRC_PATH}/game/server/fire.h
        ${SE_SRC_PATH}/game/server/fire_smoke.cpp
        ${SE_SRC_PATH}/game/server/fire_smoke.h
        ${SE_SRC_PATH}/game/server/fish.cpp
        ${SE_SRC_PATH}/game/server/fish.h
        ${SE_SRC_PATH}/game/server/fogcontroller.cpp
        ${SE_SRC_PATH}/game/server/fourwheelvehiclephysics.cpp
        ${SE_SRC_PATH}/game/server/fourwheelvehiclephysics.h
        ${SE_SRC_PATH}/game/server/func_areaportal.cpp
        ${SE_SRC_PATH}/game/server/func_areaportalbase.cpp
        ${SE_SRC_PATH}/game/server/func_areaportalbase.h
        ${SE_SRC_PATH}/game/server/func_areaportalwindow.cpp
        ${SE_SRC_PATH}/game/server/func_areaportalwindow.h
        ${SE_SRC_PATH}/game/server/func_break.cpp
        ${SE_SRC_PATH}/game/server/func_break.h
        ${SE_SRC_PATH}/game/server/func_breakablesurf.cpp
        ${SE_SRC_PATH}/game/server/func_breakablesurf.h
        ${SE_SRC_PATH}/game/server/func_dust.cpp
        ${SE_SRC_PATH}/game/shared/func_dust_shared.h
        ${SE_SRC_PATH}/game/shared/func_ladder.cpp
        ${SE_SRC_PATH}/game/server/func_ladder_endpoint.cpp
        ${SE_SRC_PATH}/game/server/func_lod.cpp
        ${SE_SRC_PATH}/game/server/func_movelinear.cpp
        ${SE_SRC_PATH}/game/server/func_movelinear.h
        ${SE_SRC_PATH}/game/server/func_occluder.cpp
        ${SE_SRC_PATH}/game/server/func_reflective_glass.cpp
        ${SE_SRC_PATH}/game/server/func_smokevolume.cpp
        ${SE_SRC_PATH}/game/server/game.cpp
        ${SE_SRC_PATH}/game/server/game.h
        ${SE_SRC_PATH}/game/server/game_ui.cpp
        ${SE_SRC_PATH}/game/server/gameinterface.cpp
        ${SE_SRC_PATH}/game/server/gameinterface.h
        ${SE_SRC_PATH}/game/shared/gamemovement.cpp
        ${SE_SRC_PATH}/game/shared/gamemovement.h
        ${SE_SRC_PATH}/game/shared/gamerules.cpp
        ${SE_SRC_PATH}/game/shared/gamerules.h
        ${SE_SRC_PATH}/game/shared/gamerules_register.cpp
        ${SE_SRC_PATH}/game/shared/GameStats.cpp
        ${SE_SRC_PATH}/game/shared/gamestats.h
        ${SE_SRC_PATH}/game/shared/gamestringpool.cpp
        ${SE_SRC_PATH}/game/shared/gamestringpool.h
        ${SE_SRC_PATH}/game/server/gametrace_dll.cpp
        ${SE_SRC_PATH}/game/shared/gamevars_shared.cpp
        ${SE_SRC_PATH}/game/shared/gamevars_shared.h
        ${SE_SRC_PATH}/game/server/gameweaponmanager.cpp
        ${SE_SRC_PATH}/game/server/gameweaponmanager.h
        ${SE_SRC_PATH}/game/server/genericactor.cpp
        ${SE_SRC_PATH}/game/server/genericmonster.cpp
        ${SE_SRC_PATH}/game/server/gib.cpp
        ${SE_SRC_PATH}/game/server/gib.h
        ${SE_SRC_PATH}/game/server/globals.cpp
        ${SE_SRC_PATH}/game/server/globalstate.cpp
        ${SE_SRC_PATH}/game/server/globalstate.h
        ${SE_SRC_PATH}/game/server/globalstate_private.h
        ${SE_SRC_PATH}/game/server/guntarget.cpp
        ${SE_SRC_PATH}/game/server/h_ai.cpp
        ${SE_SRC_PATH}/game/server/hierarchy.cpp
        ${SE_SRC_PATH}/game/server/hierarchy.h
        ${SE_SRC_PATH}/common/hl2orange.spa.h
        ${SE_SRC_PATH}/game/server/hltvdirector.cpp
        ${SE_SRC_PATH}/game/server/hltvdirector.h
        ${SE_SRC_PATH}/game/shared/hintmessage.cpp
        ${SE_SRC_PATH}/game/shared/hintmessage.h
        ${SE_SRC_PATH}/game/shared/hintsystem.cpp
        ${SE_SRC_PATH}/game/shared/hintsystem.h
        ${SE_SRC_PATH}/game/shared/ichoreoeventcallback.h
        ${SE_SRC_PATH}/game/shared/igamesystem.cpp
        ${SE_SRC_PATH}/game/shared/igamesystem.h
        ${SE_SRC_PATH}/game/server/info_camera_link.cpp
        ${SE_SRC_PATH}/game/server/info_camera_link.h
        ${SE_SRC_PATH}/game/server/info_overlay_accessor.cpp
        ${SE_SRC_PATH}/game/server/init_factory.h
        ${SE_SRC_PATH}/game/server/intermission.cpp
        ${SE_SRC_PATH}/public/interpolatortypes.h
        ${SE_SRC_PATH}/game/shared/interval.h
        ${SE_SRC_PATH}/public/iregistry.h
        ${SE_SRC_PATH}/game/shared/iscenetokenprocessor.h
        ${SE_SRC_PATH}/game/server/iservervehicle.h
        ${SE_SRC_PATH}/game/server/item_world.cpp
        ${SE_SRC_PATH}/game/server/items.h
        ${SE_SRC_PATH}/public/ivoiceserver.h
        ${SE_SRC_PATH}/public/keyframe/keyframe.h
        ${SE_SRC_PATH}/game/server/lightglow.cpp
        ${SE_SRC_PATH}/game/server/lights.cpp
        ${SE_SRC_PATH}/game/server/lights.h
        ${SE_SRC_PATH}/game/server/locksounds.h
        ${SE_SRC_PATH}/game/server/logic_measure_movement.cpp
        ${SE_SRC_PATH}/game/server/logic_navigation.cpp
        ${SE_SRC_PATH}/game/server/logicauto.cpp
        ${SE_SRC_PATH}/game/server/logicentities.cpp
        ${SE_SRC_PATH}/game/server/logicrelay.cpp
        ${SE_SRC_PATH}/game/server/mapentities.cpp
        ${SE_SRC_PATH}/game/shared/mapentities_shared.cpp
        ${SE_SRC_PATH}/game/server/maprules.cpp
        ${SE_SRC_PATH}/game/server/maprules.h
        ${SE_SRC_PATH}/game/server/MaterialModifyControl.cpp
        ${SE_SRC_PATH}/public/mathlib/mathlib.h
        ${SE_SRC_PATH}/game/server/message_entity.cpp
        ${SE_SRC_PATH}/public/model_types.h
        ${SE_SRC_PATH}/game/server/modelentities.cpp
        ${SE_SRC_PATH}/game/shared/ModelSoundsCache.cpp
        ${SE_SRC_PATH}/game/server/movehelper_server.cpp
        ${SE_SRC_PATH}/game/server/movehelper_server.h
        ${SE_SRC_PATH}/game/server/movement.cpp
        ${SE_SRC_PATH}/game/shared/movevars_shared.cpp
        ${SE_SRC_PATH}/game/server/movie_explosion.h
        ${SE_SRC_PATH}/game/shared/multiplay_gamerules.cpp
        ${SE_SRC_PATH}/game/shared/multiplay_gamerules.h
        ${SE_SRC_PATH}/game/server/ndebugoverlay.cpp
        ${SE_SRC_PATH}/game/server/ndebugoverlay.h
        ${SE_SRC_PATH}/game/server/networkstringtable_gamedll.h
        ${SE_SRC_PATH}/public/networkstringtabledefs.h
        ${SE_SRC_PATH}/game/server/npc_vehicledriver.cpp
        ${SE_SRC_PATH}/game/shared/obstacle_pushaway.cpp
        ${SE_SRC_PATH}/game/shared/obstacle_pushaway.h
        ${SE_SRC_PATH}/game/server/particle_fire.h
        ${SE_SRC_PATH}/game/server/particle_light.cpp
        ${SE_SRC_PATH}/game/server/particle_light.h
        ${SE_SRC_PATH}/game/shared/particle_parse.cpp
        ${SE_SRC_PATH}/game/shared/particle_parse.h
        ${SE_SRC_PATH}/game/server/particle_smokegrenade.h
        ${SE_SRC_PATH}/game/server/particle_system.cpp
        ${SE_SRC_PATH}/game/shared/particlesystemquery.cpp
        ${SE_SRC_PATH}/game/server/pathcorner.cpp
        ${SE_SRC_PATH}/game/server/pathtrack.cpp
        ${SE_SRC_PATH}/game/server/pathtrack.h
        ${SE_SRC_PATH}/public/vphysics/performance.h
        ${SE_SRC_PATH}/game/server/phys_controller.cpp
        ${SE_SRC_PATH}/game/server/phys_controller.h
        ${SE_SRC_PATH}/game/server/physconstraint.cpp
        ${SE_SRC_PATH}/game/server/physconstraint.h
        ${SE_SRC_PATH}/game/server/physics.cpp
        ${SE_SRC_PATH}/game/server/physics.h
        ${SE_SRC_PATH}/game/server/physics_bone_follower.cpp
        ${SE_SRC_PATH}/game/server/physics_cannister.cpp
        ${SE_SRC_PATH}/game/server/physics_collisionevent.h
        ${SE_SRC_PATH}/game/server/physics_fx.cpp
        ${SE_SRC_PATH}/game/server/physics_impact_damage.cpp
        ${SE_SRC_PATH}/game/server/pushentity.h
        ${SE_SRC_PATH}/game/server/physics_main.cpp
        ${SE_SRC_PATH}/game/shared/physics_main_shared.cpp
        ${SE_SRC_PATH}/game/server/physics_npc_solver.cpp
        ${SE_SRC_PATH}/game/server/physics_npc_solver.h
        ${SE_SRC_PATH}/game/server/physics_prop_ragdoll.cpp
        ${SE_SRC_PATH}/game/server/physics_prop_ragdoll.h
        ${SE_SRC_PATH}/game/shared/physics_saverestore.cpp
        ${SE_SRC_PATH}/game/shared/physics_saverestore.h
        ${SE_SRC_PATH}/game/shared/physics_shared.cpp
        ${SE_SRC_PATH}/game/shared/physics_shared.h
        ${SE_SRC_PATH}/game/server/physobj.cpp
        ${SE_SRC_PATH}/game/server/physobj.h
        ${SE_SRC_PATH}/game/server/player.cpp
        ${SE_SRC_PATH}/game/server/player.h
        ${SE_SRC_PATH}/game/server/player_command.cpp
        ${SE_SRC_PATH}/game/server/player_command.h
        ${SE_SRC_PATH}/game/server/player_lagcompensation.cpp
        ${SE_SRC_PATH}/game/server/player_pickup.cpp
        ${SE_SRC_PATH}/game/server/player_pickup.h
        ${SE_SRC_PATH}/game/server/player_resource.cpp
        ${SE_SRC_PATH}/game/server/player_resource.h
        ${SE_SRC_PATH}/game/server/playerinfomanager.cpp
        ${SE_SRC_PATH}/game/server/playerlocaldata.cpp
        ${SE_SRC_PATH}/game/server/playerlocaldata.h
        ${SE_SRC_PATH}/game/server/plugin_check.cpp
        ${SE_SRC_PATH}/game/shared/point_bonusmaps_accessor.cpp
        ${SE_SRC_PATH}/game/shared/point_bonusmaps_accessor.h
        ${SE_SRC_PATH}/game/server/point_camera.cpp
        ${SE_SRC_PATH}/game/server/point_camera.h
        ${SE_SRC_PATH}/game/server/point_devshot_camera.cpp
        ${SE_SRC_PATH}/game/server/point_playermoveconstraint.cpp
        ${SE_SRC_PATH}/game/shared/point_posecontroller.cpp
        ${SE_SRC_PATH}/game/shared/point_posecontroller.h
        ${SE_SRC_PATH}/game/server/point_spotlight.cpp
        ${SE_SRC_PATH}/game/server/point_template.cpp
        ${SE_SRC_PATH}/game/server/point_template.h
        ${SE_SRC_PATH}/game/server/pointanglesensor.cpp
        ${SE_SRC_PATH}/game/server/PointAngularVelocitySensor.cpp
        ${SE_SRC_PATH}/game/server/pointhurt.cpp
        ${SE_SRC_PATH}/game/server/pointteleport.cpp
        ${SE_SRC_PATH}/public/mathlib/polyhedron.h
        ${SE_SRC_PATH}/game/shared/positionwatcher.h
        ${SE_SRC_PATH}/game/shared/precache_register.cpp
        ${SE_SRC_PATH}/game/shared/precache_register.h
        ${SE_SRC_PATH}/game/shared/predictableid.cpp
        ${SE_SRC_PATH}/game/shared/predictableid.h
        ${SE_SRC_PATH}/game/server/props.cpp
        ${SE_SRC_PATH}/game/server/props.h
        ${SE_SRC_PATH}/game/shared/props_shared.cpp
        ${SE_SRC_PATH}/game/shared/querycache.cpp
        ${SE_SRC_PATH}/game/server/ragdoll_manager.cpp
        ${SE_SRC_PATH}/game/shared/ragdoll_shared.cpp
        ${SE_SRC_PATH}/game/server/RagdollBoogie.cpp
        ${SE_SRC_PATH}/game/server/RagdollBoogie.h
        ${SE_SRC_PATH}/game/server/recipientfilter.cpp
        ${SE_SRC_PATH}/game/server/recipientfilter.h
        ${SE_SRC_PATH}/game/server/rope.cpp
        ${SE_SRC_PATH}/game/server/rope.h
        ${SE_SRC_PATH}/game/shared/rope_helpers.cpp
        ${SE_SRC_PATH}/public/rope_physics.h
        ${SE_SRC_PATH}/public/rope_shared.h
        ${SE_SRC_PATH}/game/shared/saverestore.cpp
        ${SE_SRC_PATH}/game/shared/saverestore.h
        ${SE_SRC_PATH}/game/shared/saverestore_bitstring.h
        ${SE_SRC_PATH}/game/server/saverestore_gamedll.cpp
        ${SE_SRC_PATH}/game/shared/saverestore_utlsymbol.h
        ${SE_SRC_PATH}/game/shared/saverestore_utlvector.h
        ${SE_SRC_PATH}/game/shared/SceneCache.cpp
        ${SE_SRC_PATH}/game/server/sceneentity.cpp
        ${SE_SRC_PATH}/game/server/sceneentity.h
        ${SE_SRC_PATH}/game/shared/sceneentity_shared.cpp
        ${SE_SRC_PATH}/game/server/scratchpad_gamedll_helpers.cpp
        ${SE_SRC_PATH}/game/server/scripted.cpp
        ${SE_SRC_PATH}/game/server/scripted.h
        ${SE_SRC_PATH}/game/server/scriptedtarget.cpp
        ${SE_SRC_PATH}/game/server/scriptedtarget.h
        ${SE_SRC_PATH}/game/shared/scriptevent.h
        ${SE_SRC_PATH}/game/server/sendproxy.cpp
        ${SE_SRC_PATH}/game/shared/sequence_Transitioner.cpp
        ${SE_SRC_PATH}/game/server/serverbenchmark_base.cpp
        ${SE_SRC_PATH}/game/server/serverbenchmark_base.h
        ${SE_SRC_PATH}/public/server_class.h
        ${SE_SRC_PATH}/game/server/ServerNetworkProperty.cpp
        ${SE_SRC_PATH}/game/server/ServerNetworkProperty.h
        ${SE_SRC_PATH}/game/server/shadowcontrol.cpp
        ${SE_SRC_PATH}/public/shattersurfacetypes.h
        ${SE_SRC_PATH}/game/shared/sheetsimulator.h
        ${SE_SRC_PATH}/public/simple_physics.h
        ${SE_SRC_PATH}/game/shared/simtimer.cpp
        ${SE_SRC_PATH}/game/shared/simtimer.h
        ${SE_SRC_PATH}/game/shared/singleplay_gamerules.cpp
        ${SE_SRC_PATH}/game/shared/singleplay_gamerules.h
        ${SE_SRC_PATH}/game/server/SkyCamera.cpp
        ${SE_SRC_PATH}/game/server/slideshow_display.cpp
        ${SE_SRC_PATH}/game/server/sound.cpp
        ${SE_SRC_PATH}/game/shared/SoundEmitterSystem.cpp
        ${SE_SRC_PATH}/game/server/soundent.cpp
        ${SE_SRC_PATH}/game/server/soundent.h
        ${SE_SRC_PATH}/game/shared/soundenvelope.cpp
        ${SE_SRC_PATH}/public/SoundParametersInternal.cpp
        ${SE_SRC_PATH}/game/server/soundscape.cpp
        ${SE_SRC_PATH}/game/server/soundscape.h
        ${SE_SRC_PATH}/game/server/soundscape_system.cpp
        ${SE_SRC_PATH}/game/server/spark.h
        ${SE_SRC_PATH}/game/server/spotlightend.cpp
        ${SE_SRC_PATH}/game/server/spotlightend.h
        ${SE_SRC_PATH}/game/shared/Sprite.cpp
        ${SE_SRC_PATH}/game/shared/Sprite.h
        ${SE_SRC_PATH}/game/server/sprite_perfmonitor.cpp
        ${SE_SRC_PATH}/game/shared/SpriteTrail.h
        ${SE_SRC_PATH}/public/vphysics/stats.h
        ${SE_SRC_PATH}/public/steam/steam_api.h
        ${SE_SRC_PATH}/public/stringregistry.h
        ${SE_SRC_PATH}/game/shared/studio_shared.cpp
        ${SE_SRC_PATH}/game/server/subs.cpp
        ${SE_SRC_PATH}/game/server/sun.cpp
        ${SE_SRC_PATH}/game/server/tactical_mission.cpp
        ${SE_SRC_PATH}/game/server/tactical_mission.h
        ${SE_SRC_PATH}/game/shared/takedamageinfo.cpp
        ${SE_SRC_PATH}/game/server/tanktrain.cpp
        ${SE_SRC_PATH}/game/server/team.cpp
        ${SE_SRC_PATH}/game/server/team.h
        ${SE_SRC_PATH}/game/shared/teamplay_gamerules.cpp
        ${SE_SRC_PATH}/game/shared/teamplay_gamerules.h
        ${SE_SRC_PATH}/game/shared/tempentity.h
        ${SE_SRC_PATH}/game/server/TemplateEntities.cpp
        ${SE_SRC_PATH}/game/server/TemplateEntities.h
        ${SE_SRC_PATH}/game/server/tempmonster.cpp
        ${SE_SRC_PATH}/game/server/tesla.cpp
        ${SE_SRC_PATH}/game/shared/test_ehandle.cpp
        ${SE_SRC_PATH}/game/server/test_proxytoggle.cpp
        ${SE_SRC_PATH}/game/server/test_stressentities.cpp
        ${SE_SRC_PATH}/game/server/testfunctions.cpp
        ${SE_SRC_PATH}/game/server/testtraceline.cpp
        ${SE_SRC_PATH}/game/server/textstatsmgr.cpp
        ${SE_SRC_PATH}/game/server/timedeventmgr.cpp
        ${SE_SRC_PATH}/game/server/trains.cpp
        ${SE_SRC_PATH}/game/server/trains.h
        ${SE_SRC_PATH}/game/server/triggers.cpp
        ${SE_SRC_PATH}/game/server/triggers.h
        ${SE_SRC_PATH}/game/shared/usercmd.cpp
        ${SE_SRC_PATH}/game/server/util.cpp
        ${SE_SRC_PATH}/game/server/util.h
        ${SE_SRC_PATH}/game/shared/util_shared.cpp
        ${SE_SRC_PATH}/game/server/variant_t.cpp
        ${SE_SRC_PATH}/game/server/vehicle_base.cpp
        ${SE_SRC_PATH}/game/server/vehicle_baseserver.cpp
        ${SE_SRC_PATH}/game/server/vehicle_sounds.h
        ${SE_SRC_PATH}/game/shared/vehicle_viewblend_shared.cpp
        ${SE_SRC_PATH}/game/server/vguiscreen.cpp
        ${SE_SRC_PATH}/game/server/vguiscreen.h
        ${SE_SRC_PATH}/public/mathlib/vmatrix.h
        ${SE_SRC_PATH}/game/shared/voice_common.h
        ${SE_SRC_PATH}/game/shared/voice_gamemgr.cpp
        ${SE_SRC_PATH}/game/shared/voice_gamemgr.h
        ${SE_SRC_PATH}/game/server/waterbullet.cpp
        ${SE_SRC_PATH}/game/server/waterbullet.h
        ${SE_SRC_PATH}/game/server/WaterLODControl.cpp
        ${SE_SRC_PATH}/game/server/wcedit.cpp
        ${SE_SRC_PATH}/game/server/wcedit.h
        ${SE_SRC_PATH}/game/shared/weapon_parse.cpp
        ${SE_SRC_PATH}/game/shared/weapon_parse.h
        ${SE_SRC_PATH}/game/shared/weapon_proficiency.cpp
        ${SE_SRC_PATH}/game/shared/weapon_proficiency.h
        ${SE_SRC_PATH}/game/server/weight_button.cpp
        ${SE_SRC_PATH}/game/server/world.cpp
        ${SE_SRC_PATH}/game/server/world.h
        ${SE_SRC_PATH}/game/shared/mp_shareddefs.cpp
        ${SE_SRC_PATH}/game/shared/SharedFunctorUtils.h
        ${SE_SRC_PATH}/game/server/vote_controller.h
        ${SE_SRC_PATH}/game/server/vote_controller.cpp
        ${SE_SRC_PATH}/public/haptics/haptic_msgs.cpp
        ${SE_SRC_PATH}/public/bone_setup.cpp
        ${SE_SRC_PATH}/public/collisionutils.cpp
        ${SE_SRC_PATH}/public/dt_send.cpp
        ${SE_SRC_PATH}/public/dt_utlvector_common.cpp
        ${SE_SRC_PATH}/public/dt_utlvector_send.cpp
        ${SE_SRC_PATH}/public/editor_sendcommand.cpp
        ${SE_SRC_PATH}/public/filesystem_helpers.cpp
        ${SE_SRC_PATH}/game/server/gamehandle.cpp
        ${SE_SRC_PATH}/game/server/h_export.cpp
        ${SE_SRC_PATH}/game/server/init_factory.cpp
        ${SE_SRC_PATH}/public/interpolatortypes.cpp
        ${SE_SRC_PATH}/game/shared/interval.cpp
        ${SE_SRC_PATH}/public/keyframe/keyframe.cpp
        ${SE_SRC_PATH}/common/language.cpp
        ${SE_SRC_PATH}/common/steamid.cpp
        ${SE_SRC_PATH}/public/map_utils.cpp
        ${SE_SRC_PATH}/public/networkvar.cpp
        ${SE_SRC_PATH}/common/randoverride.cpp
        ${SE_SRC_PATH}/public/registry.cpp
        ${SE_SRC_PATH}/public/rope_physics.cpp
        ${SE_SRC_PATH}/public/scratchpad3d.cpp
        ${SE_SRC_PATH}/public/ScratchPadUtils.cpp
        ${SE_SRC_PATH}/public/server_class.cpp
        ${SE_SRC_PATH}/game/shared/sheetsimulator.cpp
        ${SE_SRC_PATH}/public/simple_physics.cpp
        ${SE_SRC_PATH}/public/stringregistry.cpp
        ${SE_SRC_PATH}/public/studio.cpp
        ${SE_SRC_PATH}/game/server/GameStats_BasicStatsFunctions.cpp
        ${SE_SRC_PATH}/game/server/basetempentity.cpp
        ${SE_SRC_PATH}/game/server/event_tempentity_tester.cpp
        ${SE_SRC_PATH}/game/server/movie_explosion.cpp
        ${SE_SRC_PATH}/game/server/particle_fire.cpp
        ${SE_SRC_PATH}/game/server/particle_smokegrenade.cpp
        ${SE_SRC_PATH}/game/server/plasma.cpp
        ${SE_SRC_PATH}/game/server/plasma.h
        ${SE_SRC_PATH}/game/server/smoke_trail.h
        ${SE_SRC_PATH}/game/server/smokestack.cpp
        ${SE_SRC_PATH}/game/server/smokestack.h
        ${SE_SRC_PATH}/game/server/smoke_trail.cpp
        ${SE_SRC_PATH}/game/shared/SpriteTrail.cpp
        ${SE_SRC_PATH}/game/server/steamjet.cpp
        ${SE_SRC_PATH}/game/server/steamjet.h
        ${SE_SRC_PATH}/game/server/te.cpp
        ${SE_SRC_PATH}/game/server/te.h
        ${SE_SRC_PATH}/game/server/te_armorricochet.cpp
        ${SE_SRC_PATH}/game/server/te_basebeam.cpp
        ${SE_SRC_PATH}/game/server/te_basebeam.h
        ${SE_SRC_PATH}/game/server/te_beamentpoint.cpp
        ${SE_SRC_PATH}/game/server/te_beaments.cpp
        ${SE_SRC_PATH}/game/server/te_beamfollow.cpp
        ${SE_SRC_PATH}/game/server/te_beamlaser.cpp
        ${SE_SRC_PATH}/game/server/te_beampoints.cpp
        ${SE_SRC_PATH}/game/server/te_beamring.cpp
        ${SE_SRC_PATH}/game/server/te_beamringpoint.cpp
        ${SE_SRC_PATH}/game/server/te_beamspline.cpp
        ${SE_SRC_PATH}/game/server/te_bloodsprite.cpp
        ${SE_SRC_PATH}/game/server/te_bloodstream.cpp
        ${SE_SRC_PATH}/game/server/te_breakmodel.cpp
        ${SE_SRC_PATH}/game/server/te_bspdecal.cpp
        ${SE_SRC_PATH}/game/server/te_bubbles.cpp
        ${SE_SRC_PATH}/game/server/te_bubbletrail.cpp
        ${SE_SRC_PATH}/game/server/te_clientprojectile.cpp
        ${SE_SRC_PATH}/game/server/te_decal.cpp
        ${SE_SRC_PATH}/game/server/te_dynamiclight.cpp
        ${SE_SRC_PATH}/game/server/te_effect_dispatch.cpp
        ${SE_SRC_PATH}/game/server/te_energysplash.cpp
        ${SE_SRC_PATH}/game/server/te_explosion.cpp
        ${SE_SRC_PATH}/game/server/te_fizz.cpp
        ${SE_SRC_PATH}/game/server/te_footprintdecal.cpp
        ${SE_SRC_PATH}/game/server/hl2/te_gaussexplosion.cpp
        ${SE_SRC_PATH}/game/server/te_glassshatter.cpp
        ${SE_SRC_PATH}/game/server/te_glowsprite.cpp
        ${SE_SRC_PATH}/game/server/te_impact.cpp
        ${SE_SRC_PATH}/game/server/te_killplayerattachments.cpp
        ${SE_SRC_PATH}/game/server/te_largefunnel.cpp
        ${SE_SRC_PATH}/game/server/te_muzzleflash.cpp
        ${SE_SRC_PATH}/game/server/te_particlesystem.cpp
        ${SE_SRC_PATH}/game/server/te_particlesystem.h
        ${SE_SRC_PATH}/game/server/te_physicsprop.cpp
        ${SE_SRC_PATH}/game/server/te_playerdecal.cpp
        ${SE_SRC_PATH}/game/server/te_projecteddecal.cpp
        ${SE_SRC_PATH}/game/server/te_showline.cpp
        ${SE_SRC_PATH}/game/server/te_smoke.cpp
        ${SE_SRC_PATH}/game/server/te_sparks.cpp
        ${SE_SRC_PATH}/game/server/te_sprite.cpp
        ${SE_SRC_PATH}/game/server/te_spritespray.cpp
        ${SE_SRC_PATH}/game/server/te_worlddecal.cpp
        ${SE_SRC_PATH}/game/shared/usermessages.cpp
        ${SE_SRC_PATH}/public/mathlib/amd3dx.h
        ${SE_SRC_PATH}/game/shared/ammodef.h
        ${SE_SRC_PATH}/game/shared/base_playeranimstate.h
        ${SE_SRC_PATH}/game/server/base_transmit_proxy.h
        ${SE_SRC_PATH}/public/basehandle.h
        ${SE_SRC_PATH}/game/server/basetempentity.h
        ${SE_SRC_PATH}/public/tier0/basetypes.h
        ${SE_SRC_PATH}/game/shared/beam_flags.h
        ${SE_SRC_PATH}/public/tier1/bitbuf.h
        ${SE_SRC_PATH}/public/bitvec.h
        ${SE_SRC_PATH}/public/bone_accessor.h
        ${SE_SRC_PATH}/public/bspfile.h
        ${SE_SRC_PATH}/public/bspflags.h
        ${SE_SRC_PATH}/public/mathlib/bumpvects.h
        ${SE_SRC_PATH}/public/tier1/characterset.h
        ${SE_SRC_PATH}/public/tier1/checksum_md5.h
        ${SE_SRC_PATH}/public/client_class.h
        ${SE_SRC_PATH}/public/client_textmessage.h
        ${SE_SRC_PATH}/public/cmodel.h
        ${SE_SRC_PATH}/public/vphysics/collision_set.h
        ${SE_SRC_PATH}/public/Color.h
        ${SE_SRC_PATH}/public/tier0/commonmacros.h
        ${SE_SRC_PATH}/public/mathlib/compressed_light_cube.h
        ${SE_SRC_PATH}/public/mathlib/compressed_vector.h
        ${SE_SRC_PATH}/public/const.h
        ${SE_SRC_PATH}/public/vphysics/constraints.h
        ${SE_SRC_PATH}/public/coordsize.h
        ${SE_SRC_PATH}/game/server/cplane.h
        ${SE_SRC_PATH}/game/server/damagemodifier.h
        ${SE_SRC_PATH}/public/datamap.h
        ${SE_SRC_PATH}/public/tier0/dbg.h
        ${SE_SRC_PATH}/game/shared/death_pose.h
        ${SE_SRC_PATH}/game/shared/decals.h
        ${SE_SRC_PATH}/public/dlight.h
        ${SE_SRC_PATH}/public/dt_common.h
        ${SE_SRC_PATH}/public/dt_recv.h
        ${SE_SRC_PATH}/public/dt_send.h
        ${SE_SRC_PATH}/public/dt_utlvector_common.h
        ${SE_SRC_PATH}/public/dt_utlvector_send.h
        ${SE_SRC_PATH}/game/shared/effect_dispatch_data.h
        ${SE_SRC_PATH}/game/shared/ehandle.h
        ${SE_SRC_PATH}/game/shared/entitydatainstantiator.h
        ${SE_SRC_PATH}/game/shared/entitylist_base.h
        ${SE_SRC_PATH}/game/shared/env_detail_controller.h
        ${SE_SRC_PATH}/game/server/EventLog.h
        ${SE_SRC_PATH}/game/shared/expressionsample.h
        ${SE_SRC_PATH}/public/tier0/fasttimer.h
        ${SE_SRC_PATH}/public/filesystem.h
        ${SE_SRC_PATH}/public/filesystem_helpers.h
        ${SE_SRC_PATH}/public/tier1/fmtstr.h
        ${SE_SRC_PATH}/game/server/fogcontroller.h
        ${SE_SRC_PATH}/public/vphysics/friction.h
        ${SE_SRC_PATH}/game/shared/func_ladder.h
        ${SE_SRC_PATH}/game/shared/gameeventdefs.h
        ${SE_SRC_PATH}/game/shared/GameEventListener.h
        ${SE_SRC_PATH}/game/shared/gamerules_register.h
        ${SE_SRC_PATH}/public/gametrace.h
        ${SE_SRC_PATH}/game/server/globals.h
        ${SE_SRC_PATH}/public/globalvars_base.h
        ${SE_SRC_PATH}/game/shared/groundlink.h
        ${SE_SRC_PATH}/game/shared/hl2/hl2_vehicle_radar.h
        ${SE_SRC_PATH}/public/iachievementmgr.h
        ${SE_SRC_PATH}/public/appframework/IAppSystem.h
        ${SE_SRC_PATH}/public/icliententity.h
        ${SE_SRC_PATH}/public/iclientnetworkable.h
        ${SE_SRC_PATH}/public/iclientrenderable.h
        ${SE_SRC_PATH}/public/iclientunknown.h
        ${SE_SRC_PATH}/public/engine/ICollideable.h
        ${SE_SRC_PATH}/public/tier0/icommandline.h
        ${SE_SRC_PATH}/public/icvar.h
        ${SE_SRC_PATH}/game/shared/IEffects.h
        ${SE_SRC_PATH}/public/engine/IEngineSound.h
        ${SE_SRC_PATH}/public/engine/IEngineTrace.h
        ${SE_SRC_PATH}/public/igameevents.h
        ${SE_SRC_PATH}/game/shared/igamemovement.h
        ${SE_SRC_PATH}/public/ihandleentity.h
        ${SE_SRC_PATH}/public/ihltv.h
        ${SE_SRC_PATH}/public/ihltvdirector.h
        ${SE_SRC_PATH}/public/vstdlib/IKeyValuesSystem.h
        ${SE_SRC_PATH}/game/server/ilagcompensationmanager.h
        ${SE_SRC_PATH}/public/vgui/ILocalize.h
        ${SE_SRC_PATH}/public/materialsystem/imaterial.h
        ${SE_SRC_PATH}/public/materialsystem/imaterialsystem.h
        ${SE_SRC_PATH}/public/materialsystem/imaterialvar.h
        ${SE_SRC_PATH}/game/shared/imovehelper.h
        ${SE_SRC_PATH}/game/shared/in_buttons.h
        ${SE_SRC_PATH}/public/inetchannelinfo.h
        ${SE_SRC_PATH}/game/shared/iplayeranimstate.h
        ${SE_SRC_PATH}/game/shared/ipredictionsystem.h
        ${SE_SRC_PATH}/public/irecipientfilter.h
        ${SE_SRC_PATH}/public/isaverestore.h
        ${SE_SRC_PATH}/public/iscratchpad3d.h
        ${SE_SRC_PATH}/public/iserverentity.h
        ${SE_SRC_PATH}/public/iservernetworkable.h
        ${SE_SRC_PATH}/public/iserverunknown.h
        ${SE_SRC_PATH}/public/SoundEmitterSystem/isoundemittersystembase.h
        ${SE_SRC_PATH}/public/ispatialpartition.h
        ${SE_SRC_PATH}/public/engine/IStaticPropMgr.h
        ${SE_SRC_PATH}/game/shared/itempents.h
        ${SE_SRC_PATH}/public/engine/ivdebugoverlay.h
        ${SE_SRC_PATH}/game/shared/IVehicle.h
        ${SE_SRC_PATH}/public/engine/ivmodelinfo.h
        ${SE_SRC_PATH}/public/tier1/KeyValues.h
        ${SE_SRC_PATH}/common/language.h
        ${SE_SRC_PATH}/public/tier0/l2cache.h
        ${SE_SRC_PATH}/game/server/logicrelay.h
        ${SE_SRC_PATH}/public/map_utils.h
        ${SE_SRC_PATH}/game/server/mapentities.h
        ${SE_SRC_PATH}/game/shared/mapentities_shared.h
        ${SE_SRC_PATH}/public/tier0/mem.h
        ${SE_SRC_PATH}/public/tier0/memalloc.h
        ${SE_SRC_PATH}/public/tier0/memdbgoff.h
        ${SE_SRC_PATH}/public/tier0/memdbgon.h
        ${SE_SRC_PATH}/game/server/modelentities.h
        ${SE_SRC_PATH}/game/shared/movevars_shared.h
        ${SE_SRC_PATH}/public/networkvar.h
        ${SE_SRC_PATH}/game/server/npc_vehicledriver.h
        ${SE_SRC_PATH}/game/shared/npcevent.h
        ${SE_SRC_PATH}/public/vphysics/object_hash.h
        ${SE_SRC_PATH}/game/server/particle_system.h
        ${SE_SRC_PATH}/game/server/physics_cannister.h
        ${SE_SRC_PATH}/game/server/physics_fx.h
        ${SE_SRC_PATH}/game/server/physics_impact_damage.h
        ${SE_SRC_PATH}/public/tier0/platform.h
        ${SE_SRC_PATH}/public/vphysics/player_controller.h
        ${SE_SRC_PATH}/game/server/playerinfomanager.h
        ${SE_SRC_PATH}/game/shared/playernet_vars.h
        ${SE_SRC_PATH}/public/PlayerState.h
        ${SE_SRC_PATH}/game/shared/precipitation_shared.h
        ${SE_SRC_PATH}/game/shared/predictable_entity.h
        ${SE_SRC_PATH}/game/shared/predictioncopy.h
        ${SE_SRC_PATH}/public/tier1/processor_detect.h
        ${SE_SRC_PATH}/game/shared/querycache.h
        ${SE_SRC_PATH}/game/shared/props_shared.h
        ${SE_SRC_PATH}/public/tier0/protected_things.h
        ${SE_SRC_PATH}/public/vstdlib/random.h
        ${SE_SRC_PATH}/game/shared/rope_helpers.h
        ${SE_SRC_PATH}/game/shared/saverestore_stringtable.h
        ${SE_SRC_PATH}/game/shared/saverestore_utlclass.h
        ${SE_SRC_PATH}/game/shared/saverestore_utlmap.h
        ${SE_SRC_PATH}/game/shared/saverestore_utlrbtree.h
        ${SE_SRC_PATH}/public/saverestoretypes.h
        ${SE_SRC_PATH}/public/scratchpad3d.h
        ${SE_SRC_PATH}/game/server/scratchpad_gamedll_helpers.h
        ${SE_SRC_PATH}/public/ScratchPadUtils.h
        ${SE_SRC_PATH}/game/server/sendproxy.h
        ${SE_SRC_PATH}/public/shake.h
        ${SE_SRC_PATH}/game/shared/shared_classnames.h
        ${SE_SRC_PATH}/game/shared/shareddefs.h
        ${SE_SRC_PATH}/game/shared/sharedInterface.h
        ${SE_SRC_PATH}/game/shared/shot_manipulator.h
        ${SE_SRC_PATH}/game/server/SkyCamera.h
        ${SE_SRC_PATH}/public/soundchars.h
        ${SE_SRC_PATH}/game/shared/soundenvelope.h
        ${SE_SRC_PATH}/public/soundflags.h
        ${SE_SRC_PATH}/game/server/soundscape_system.h
        ${SE_SRC_PATH}/public/stdstring.h
        ${SE_SRC_PATH}/public/string_t.h
        ${SE_SRC_PATH}/public/tier1/stringpool.h
        ${SE_SRC_PATH}/public/tier1/strtools.h
        ${SE_SRC_PATH}/public/studio.h
        ${SE_SRC_PATH}/game/shared/sun_shared.h
        ${SE_SRC_PATH}/game/shared/takedamageinfo.h
        ${SE_SRC_PATH}/game/server/te_effect_dispatch.h
        ${SE_SRC_PATH}/game/server/tesla.h
        ${SE_SRC_PATH}/game/server/test_stressentities.h
        ${SE_SRC_PATH}/game/server/textstatsmgr.h
        ${SE_SRC_PATH}/public/texture_group_names.h
        ${SE_SRC_PATH}/game/server/timedeventmgr.h
        ${SE_SRC_PATH}/game/shared/usercmd.h
        ${SE_SRC_PATH}/game/shared/usermessages.h
        ${SE_SRC_PATH}/game/shared/util_shared.h
        ${SE_SRC_PATH}/public/UtlCachedFileData.h
        ${SE_SRC_PATH}/public/tier1/utldict.h
        ${SE_SRC_PATH}/public/tier1/utlfixedmemory.h
        ${SE_SRC_PATH}/public/tier1/utlhash.h
        ${SE_SRC_PATH}/public/tier1/utllinkedlist.h
        ${SE_SRC_PATH}/public/tier1/utlmap.h
        ${SE_SRC_PATH}/public/tier1/utlmemory.h
        ${SE_SRC_PATH}/public/tier1/utlmultilist.h
        ${SE_SRC_PATH}/public/tier1/utlpriorityqueue.h
        ${SE_SRC_PATH}/public/tier1/utlrbtree.h
        ${SE_SRC_PATH}/public/tier1/UtlSortVector.h
        ${SE_SRC_PATH}/public/tier1/utlvector.h
        ${SE_SRC_PATH}/public/vallocator.h
        ${SE_SRC_PATH}/game/server/variant_t.h
        ${SE_SRC_PATH}/public/vcollide.h
        ${SE_SRC_PATH}/public/vcollide_parse.h
        ${SE_SRC_PATH}/public/tier0/vcr_shared.h
        ${SE_SRC_PATH}/public/tier0/vcrmode.h
        ${SE_SRC_PATH}/public/mathlib/vector.h
        ${SE_SRC_PATH}/public/mathlib/vector2d.h
        ${SE_SRC_PATH}/public/mathlib/vector4d.h
        ${SE_SRC_PATH}/game/server/vehicle_base.h
        ${SE_SRC_PATH}/game/server/vehicle_baseserver.h
        ${SE_SRC_PATH}/game/shared/vehicle_viewblend_shared.h
        ${SE_SRC_PATH}/public/vphysics/vehicles.h
        ${SE_SRC_PATH}/public/vgui/VGUI.h
        ${SE_SRC_PATH}/public/vphysics_interface.h
        ${SE_SRC_PATH}/game/shared/vphysics_sound.h
        ${SE_SRC_PATH}/public/mathlib/vplane.h
        ${SE_SRC_PATH}/public/tier0/vprof.h
        ${SE_SRC_PATH}/public/vstdlib/vstdlib.h
        ${SE_SRC_PATH}/public/winlite.h
        ${SE_SRC_PATH}/public/worldsize.h
        ${SE_SRC_PATH}/public/zip_uncompressed.h
        ${SE_SRC_PATH}/game/shared/mp_shareddefs.h
        ${SE_SRC_PATH}/game/shared/econ/ihasowner.h
        ${SE_SRC_PATH}/game/server/entity_tools_server.cpp
        ${SE_SRC_PATH}/game/server/toolframework_server.cpp
        ${SE_SRC_PATH}/game/server/toolframework_server.h
        )

if(SE_WIN32)
    target_sources(server_base INTERFACE
            ${SE_SRC_PATH}/public/haptics/haptic_utils.cpp	#[$WIN32]
            ${SE_SRC_PATH}/public/haptics/haptic_utils.h	#[$WIN32]
            )
endif()
target_include_directories(server_base INTERFACE
        ${SE_SRC_PATH}/game/server
        ${SE_SRC_PATH}/game/shared
        ${SE_SRC_PATH}/game/shared/econ
        ${SE_SRC_PATH}/game/server/NextBot
        ${SE_SRC_PATH}/utils/common
        ${SE_SRC_PATH}/public
        ${SE_SRC_PATH}/public/tier0
        ${SE_SRC_PATH}/public/tier1
        ${SE_SRC_PATH}/common
        ${SE_SRC_PATH}/public
        )
target_compile_definitions(server_base INTERFACE -DGAME_DLL VECTOR -DVERSION_SAFE_STEAM_API_INTERFACES -DPROTECTED_THINGS_ENABLE -Dstrncpy=use_Q_strncpy_instead -D_snprintf=use_Q_snprintf_instead)
if(SE_POSIX)
    target_compile_definitions(server_base INTERFACE -DSWDS)
endif()
if(SE_WIN32)
    target_compile_definitions(server_base INTERFACE fopen=dont_use_fopen)
endif()
target_link_libraries(server_base INTERFACE platform_config video_config choreoobjects dmxloader mathlib particles tier0 tier1 tier2 tier3 steam_api)

if(SE_WIN32)
    target_link_libraries(server_base INTERFACE winmm)
endif()
if(SE_OSX)
    target_link_libraries(server_base INTERFACE iconv)
endif()

add_library(server_relay INTERFACE)
target_sources(server_relay INTERFACE
        ${SE_SRC_PATH}/game/shared/replay_gamestats_shared.cpp	#[$BUILD_REPLAY]
        ${SE_SRC_PATH}/game/shared/replay_gamestats_shared.h	#[$BUILD_REPLAY]
)

add_library(nav_mesh INTERFACE)
target_sources(nav_mesh INTERFACE
        ${SE_SRC_PATH}/game/server/nav.h
        ${SE_SRC_PATH}/game/server/nav_area.cpp
        ${SE_SRC_PATH}/game/server/nav_area.h
        ${SE_SRC_PATH}/game/server/nav_colors.cpp
        ${SE_SRC_PATH}/game/server/nav_colors.h
        ${SE_SRC_PATH}/game/server/nav_edit.cpp
        ${SE_SRC_PATH}/game/server/nav_entities.cpp
        ${SE_SRC_PATH}/game/server/nav_entities.h
        ${SE_SRC_PATH}/game/server/nav_file.cpp
        ${SE_SRC_PATH}/game/server/nav_generate.cpp
        ${SE_SRC_PATH}/game/server/nav_ladder.cpp
        ${SE_SRC_PATH}/game/server/nav_ladder.h
        ${SE_SRC_PATH}/game/server/nav_merge.cpp
        ${SE_SRC_PATH}/game/server/nav_mesh.cpp
        ${SE_SRC_PATH}/game/server/nav_mesh.h
        ${SE_SRC_PATH}/game/server/nav_mesh_factory.cpp
        ${SE_SRC_PATH}/game/server/nav_node.cpp
        ${SE_SRC_PATH}/game/server/nav_node.h
        ${SE_SRC_PATH}/game/server/nav_pathfind.h
        ${SE_SRC_PATH}/game/server/nav_simplify.cpp
)
target_compile_definitions(nav_mesh INTERFACE -DUSE_NAV_MESH)
